export const OPTIONS_LIST = [
  'Admin 1',
  'Country Admin 1',
  'User 1',
  'Admin 2',
  'Country Admin 2',
  'User 2',
  'Admin 3',
  'Country Admin 3',
  'User 3',
  'Admin 4',
  'Country Admin 4',
  'User 4',
  'Admin 5',
  'Country Admin 5',
  'User 5',
  'Admin 6',
  'Country Admin 6',
  'User 6',
  'Admin 7',
  'Country Admin 7',
  'User 7',
]
