import { NgModule } from '@angular/core'
import { Route, RouterModule } from '@angular/router'
import { AccordionExamplePage } from './pages/accordion-example/accordion-example.page'
import { AgGridTableExamplePage } from './pages/ag-grid-table-example/ag-grid-table-example.page'
import { AgGridTableLoadMoreExamplePage } from './pages/ag-grid-table-example/ag-grid-table-load-more-example.page'
import { AutocompleteExamplePage } from './pages/autocomplete-example/autocomplete-example.page'
import { AvatarsVC } from './pages/vc/avatars/avatarsVC'
import { BannerExamplePage } from './pages/banner-example/banner-example.page'
import { ButtonsVC } from './pages/vc/buttons/buttonsVC'
import { CardsVC } from './pages/vc/cards/cardsVC'
import { CheckboxesVC } from './pages/vc/checkboxes/checkboxesVC'
import { CountersVC } from './pages/vc/counters/countersVC'
import { DatepickerExamplePage } from './pages/datepicker-example/datepicker-example.page'
import { FileUploadExamplePage } from './pages/file-upload-example/file-upload.page'
import { ModalExamplePage } from './pages/modal-example/modal-example.page'
import { RadioButtonsExamplePage } from './pages/radio-buttons-example/radio-buttons-example.page'
import { RichtextExamplePage } from './pages/richtext-example/richtext-example.page'
import { InputsExampleVC } from './pages/vc/inputs/inputsVC'
import { TogglesVC } from './pages/vc/toggles/togglesVC'
import { TopbarExamplePage } from './pages/topbar-example/topbar-example.page'
import { VCComponent } from './components/vc/vc.component'
import { BackToTopButtonExamplePage } from './pages/back-to-top-button-example/back-to-top-button-example.page'
import { MenuContextExamplePage } from './pages/menu-context-example/menu-context-example.page'
import { FormExamplePage } from './pages/form-example/form-example.page'
import { AutocompleteVC } from './pages/vc/autocomplete/autocompleteVC'
import { BreadcrumbsVC } from './pages/vc/breadcrumbs/breadcrumbsVC'
import { CheckboxExamplePage } from './pages/checkbox-example/checkbox-example.page'
import { ColorPickerExamplePage } from './pages/color-picker-example/color-picker-example.page'
import { InlineEditVC } from './pages/vc/inline-edit/inline-editVC'
import { MenuContextVC } from './pages/vc/menu-context/menu-contextVC'
import { PopoversVC } from './pages/vc/popovers/popoversVC'
import { SelectsVC } from './pages/vc/selects/selectsVC'
import { SelectsExamplePage } from './pages/selects-example/selects-example.page'
import { SteppersVC } from './pages/vc/steppers/steppersVC'
import { TextAreaVC } from './pages/vc/text-area/text-areaVC'
import { ToggleExamplePage } from './pages/toggle-example/toggle-example.page'
import { AccordionsVC } from './pages/vc/accordions/accordionsVC'
import { CardGroupVC } from './pages/vc/card-group/card-group'
import { DatepickerVC } from './pages/vc/datepicker/datepickerVC'
import { DividerVC } from './pages/vc/divider/dividerVC'
import { ExpandableCardVC } from './pages/vc/expandable-card/expandable-cardVC'
import { FileUploadVC } from './pages/vc/file-upload/file-uploadVC'
import { GridCssVC } from './pages/vc/grid-css/grid-cssVC'
import { IconsVC } from './pages/vc/icons/iconsVC'
import { ImagesVC } from './pages/vc/images/imagesVC'
import { InlineMessagesVC } from './pages/vc/inline-messages/inline-messagesVC'
import { LabelsVC } from './pages/vc/labels/labelsVC'
import { ListItemsVC } from './pages/vc/list-items/list-itemsVC'
import { ModalsVC } from './pages/vc/modals/modalsVC'
import { NavSidebarVC } from './pages/vc/nav-sidebar/nav-sidebarVC'
import { PaginationsVC } from './pages/vc/paginations/paginationsVC'
import { PillsVC } from './pages/vc/pills/pillsVC'
import { ProgressIndicatorsVC } from './pages/vc/progress-indicators/progress-indicatorsVC'
import { RadioButtonsVC } from './pages/vc/radio-buttons/radio-buttonsVC'
import { SegmentedControlsVC } from './pages/vc/segmented-controls/segmented-controlsVC'
import { SlidersVC } from './pages/vc/sliders/slidersVC'
import { SpinnersVC } from './pages/vc/spinners/spinnersVC'
import { SkeletonVC } from './pages/vc/skeleton/skeletonVC'
import { TabsVC } from './pages/vc/tabs/tabsVC'
import { TagsVC } from './pages/vc/tags/tagsVC'
import { ToastsVC } from './pages/vc/toasts/toastsVC'
import { TooltipsVC } from './pages/vc/tooltips/tooltipsVC'
import { TopbarVC } from './pages/vc/topbar/topbarVC'
import { TreesVC } from './pages/vc/trees/treesVC'
import { TypographyVC } from './pages/vc/typography/typographyVC'
import { SwiperExamplePage } from './pages/swiper-example/swiper-example.page'
import { CountriesVC } from './pages/vc/icons/countries/countriesVC'
import { SearchVC } from './pages/vc/search/searchVC'
import { SelectsMultipleVC } from './pages/vc/selects-multiple/selects-multipleVC'
import { SelectsSingleVC } from './pages/vc/selects-single/selects-singleVC'
import { SelectsTextVC } from './pages/vc/selects-text/selects-textVC'
import { CombinedInputsVC } from './pages/vc/combined-inputs/combined-inputsVC'
import { StickyBarExamplePage } from './pages/sticky-bar-example/sticky-bar.page'
import { LoadMoreVC } from './pages/vc/load-more/load-moreVC'
import { TimePickerExamplePage } from './pages/time-picker-example/time-picker.page'
import { ChatInputExamplePage } from './pages/chat-input-example/chat-input-example.page'
import { SelectsCombinedVC } from './pages/vc/selects-combined/selects-combinedVC'
import { SingleSelectPage } from './pages/single-select-example/single-select-example.page'
import { MultipleSelectPage } from './pages/multiple-select-example/multiple-select-example.page'
import { TextSelectPage } from './pages/text-select-example/text-select-example.page'
import { CombinedSelectPage } from './pages/combined-select-example/combined-select-example.page'
import { AgGridTableHybridInfiniteScrollExamplePage } from './pages/ag-grid-table-example/ag-grid-table-hybrid-infinite-scroll-example.page'
import { OverlayExamplePage } from './pages/overlay-example/overlay-example.page'

const routes: Route[] = [
  {
    path: 'vc',
    component: VCComponent,
    children: [
      { path: 'accordions', component: AccordionsVC },
      { path: 'autocomplete', component: AutocompleteVC },
      { path: 'avatars', component: AvatarsVC },
      { path: 'breadcrumbs', component: BreadcrumbsVC },
      { path: 'buttons', component: ButtonsVC },
      { path: 'card-group', component: CardGroupVC },
      { path: 'cards', component: CardsVC },
      { path: 'checkboxes', component: CheckboxesVC },
      { path: 'combined-inputs', component: CombinedInputsVC },
      { path: 'counters', component: CountersVC },
      { path: 'countries', component: CountriesVC },
      { path: 'datepicker', component: DatepickerVC },
      { path: 'divider', component: DividerVC },
      { path: 'expandable-card', component: ExpandableCardVC },
      { path: 'file-upload', component: FileUploadVC },
      { path: 'grid-css', component: GridCssVC },
      { path: 'icons', component: IconsVC },
      { path: 'images', component: ImagesVC },
      { path: 'inline-edit', component: InlineEditVC },
      { path: 'inline-messages', component: InlineMessagesVC },
      { path: 'inputs', component: InputsExampleVC },
      { path: 'labels', component: LabelsVC },
      { path: 'list-items', component: ListItemsVC },
      { path: 'load-more', component: LoadMoreVC },
      { path: 'menu-context', component: MenuContextVC },
      { path: 'modals', component: ModalsVC },
      { path: 'nav-sidebar', component: NavSidebarVC },
      { path: 'pagination', component: PaginationsVC },
      { path: 'pills', component: PillsVC },
      { path: 'popovers', component: PopoversVC },
      { path: 'progress-indicators', component: ProgressIndicatorsVC },
      { path: 'radio-buttons', component: RadioButtonsVC },
      { path: 'search', component: SearchVC },
      { path: 'segmented-controls', component: SegmentedControlsVC },
      { path: 'selects', component: SelectsVC },
      { path: 'selects-multiple', component: SelectsMultipleVC },
      { path: 'selects-single', component: SelectsSingleVC },
      { path: 'selects-text', component: SelectsTextVC },
      { path: 'selects-combined', component: SelectsCombinedVC },
      { path: 'sliders', component: SlidersVC },
      { path: 'spinner', component: SpinnersVC },
      { path: 'skeleton', component: SkeletonVC },
      { path: 'stepper', component: SteppersVC },
      { path: 'tabs', component: TabsVC },
      { path: 'tags', component: TagsVC },
      { path: 'text-areas', component: TextAreaVC },
      { path: 'toasts', component: ToastsVC },
      { path: 'toggles', component: TogglesVC },
      { path: 'tooltips', component: TooltipsVC },
      { path: 'topbar', component: TopbarVC },
      { path: 'tree', component: TreesVC },
      { path: 'typography', component: TypographyVC },
    ],
  },
  { path: 'accordion', component: AccordionExamplePage },
  { path: 'ag-grid-table-pagination', component: AgGridTableExamplePage },
  { path: 'ag-grid-table-load-more', component: AgGridTableLoadMoreExamplePage },
  { path: 'ag-grid-table-infinite-scroll', component: AgGridTableExamplePage },
  { path: 'ag-grid-table-hybrid-infinite-scroll', component: AgGridTableHybridInfiniteScrollExamplePage },
  { path: 'autocomplete', component: AutocompleteExamplePage },
  { path: 'back-to-top-button', component: BackToTopButtonExamplePage },
  { path: 'banners', component: BannerExamplePage },
  { path: 'chat-input', component: ChatInputExamplePage },
  { path: 'checkboxes', component: CheckboxExamplePage },
  { path: 'color-picker', component: ColorPickerExamplePage },
  { path: 'datepickers', component: DatepickerExamplePage },
  { path: 'file-upload', component: FileUploadExamplePage },
  { path: 'form-controls', component: FormExamplePage },
  { path: 'menu-context', component: MenuContextExamplePage },
  { path: 'modals', component: ModalExamplePage },
  { path: 'overlay', component: OverlayExamplePage },
  { path: 'radio-buttons', component: RadioButtonsExamplePage },
  { path: 'rich-text', component: RichtextExamplePage },
  { path: 'search', component: SelectsExamplePage },
  { path: 'selects', component: SelectsExamplePage },
  { path: 'single-select', component: SingleSelectPage },
  { path: 'multiple-select', component: MultipleSelectPage },
  { path: 'text-select', component: TextSelectPage },
  { path: 'combined-select', component: CombinedSelectPage },
  { path: 'sticky-bar', component: StickyBarExamplePage },
  { path: 'swiper', component: SwiperExamplePage },
  { path: 'time-picker', component: TimePickerExamplePage },
  { path: 'toggles', component: ToggleExamplePage },
  { path: 'topbar', component: TopbarExamplePage },
]

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule],
})
export class AppRoutingModule {}
