import React, { useState } from 'react'
import { AutocompleteDefaultOption } from '@platform-ui-kit/components-library'
import { WppAccordion, WppAutocomplete, WppTypography, WppListItem } from '@platform-ui-kit/components-library-react'

import { countryOptions, fruitOptions, hugeListOptions } from './options'

import { ResultsView } from './ResultsView'
import { SelectedValues } from './SelectedValues'
import { InfiniteScrollWithLazyLoad } from './Examples/InfiniteScrollWithLazyLoad'
import { ServerSearch } from './Examples/ServerSearch'
import { ServerLoadSameOptionForDifferentSearch } from './Examples/ServerLoadSameOptionForDifferentSearch'
import { WithoutSimpleSearch } from './Examples/WithoutSimpleSearch'

import styles from './Autocomplete.module.scss'

export const Autocomplete = () => {
  const [basicValue, setBasicValue] = useState<AutocompleteDefaultOption[]>([
    {
      id: 5,
      label: 'Pineapple',
    },
    {
      id: 3,
      label: 'Kiwi',
    },
    {
      id: 13,
      label: 'Pear',
    },
  ])
  const [customOptionsValue, setCustomOptionsValue] = useState<AutocompleteDefaultOption[]>([])
  const [hugeListValue, setHugeListValue] = useState<AutocompleteDefaultOption[]>([])

  return (
    <>
      <div className={styles.wrapper} data-testid="autocompletes">
        <div className={styles.item}>
          <WppAutocomplete
            required
            name="basic"
            labelConfig={{
              icon: 'wpp-icon-info',
              text: 'Basic with initial values',
              description: 'Description',
              locales: {
                optional: 'Optional',
              },
            }}
            placeholder="Select fruits"
            value={basicValue}
            onWppChange={(e: CustomEvent) => setBasicValue(e.detail.value as AutocompleteDefaultOption[])}
            data-testid="basic-autocomplete"
            multiple
            showCreateNewElement
            simpleSearch
          >
            {fruitOptions.map(option => (
              <WppListItem key={option.id} value={option} label={option.label}>
                <p slot="label">{option.label}</p>
              </WppListItem>
            ))}
            <SelectedValues
              values={basicValue}
              onCloseClick={value => setBasicValue(basicValue.filter(i => i.id !== value))}
            />
          </WppAutocomplete>
        </div>
        <div className={styles.item}>
          <WppAutocomplete
            required
            name="custom-option-labels"
            labelConfig={{ text: 'Custom option labels and modified number of tags shown when idle' }}
            placeholder="Select countries"
            value={customOptionsValue}
            onWppChange={(e: CustomEvent) => setCustomOptionsValue(e.detail.value as AutocompleteDefaultOption[])}
            data-testid="custom-autocomplete"
            autoFocus
            multiple
            showCreateNewElement
            simpleSearch
          >
            {countryOptions.map(option => (
              <WppListItem key={option.id} value={option} label={option.label}>
                <div slot="label">
                  <div className={styles.primary}>
                    <span className={styles.flag}>{option.flag}</span> {option.label}
                  </div>
                </div>
                <div className={styles.secondary} slot="caption">
                  {option.nativeName}
                </div>
              </WppListItem>
            ))}
            <SelectedValues
              values={customOptionsValue}
              onCloseClick={value => setCustomOptionsValue(customOptionsValue.filter(i => i.id !== value))}
            />
          </WppAutocomplete>

          <ResultsView value={customOptionsValue.map(i => i.id)} />
        </div>

        <div className={styles.item}>
          <WppAutocomplete
            required
            name="huge-list"
            labelConfig={{ text: 'Huge autogenerated list' }}
            placeholder="Select everything"
            value={hugeListValue}
            onWppChange={(e: CustomEvent) => setHugeListValue(e.detail.value as AutocompleteDefaultOption[])}
            multiple
            showCreateNewElement
            simpleSearch
          >
            {hugeListOptions.map(option => (
              <WppListItem key={option.id} value={option}>
                <p slot="label">{option.label}</p>
              </WppListItem>
            ))}

            <SelectedValues
              values={hugeListValue}
              onCloseClick={value => setHugeListValue(hugeListValue.filter(i => i.id !== value))}
            />
          </WppAutocomplete>

          <ResultsView value={`${hugeListValue.length} option(s) selected`} />
        </div>

        <ServerSearch />
        <InfiniteScrollWithLazyLoad />
        <ServerLoadSameOptionForDifferentSearch />
        <WithoutSimpleSearch />

        <div className={styles.item}>
          <WppAccordion size="s" expanded counter={3} text="Autocomplete in Accordion">
            <WppAutocomplete
              required
              name="basic"
              labelConfig={{ text: 'Basic with initial values' }}
              placeholder="Select fruits"
              value={basicValue}
              onWppChange={(e: CustomEvent) => setBasicValue(e.detail.value as AutocompleteDefaultOption[])}
              data-testid="basic-autocomplete"
              dropdownConfig={{ popperOptions: { strategy: 'fixed' } }}
              multiple
              showCreateNewElement
              simpleSearch
            >
              {fruitOptions.map(option => (
                <WppListItem key={option.id} value={option} label={option.label}>
                  <p slot="label">{option.label}</p>
                </WppListItem>
              ))}
              <SelectedValues
                values={basicValue}
                onCloseClick={value => setBasicValue(basicValue.filter(i => i.id !== value))}
              />
            </WppAutocomplete>
          </WppAccordion>
        </div>
      </div>

      <div className={styles.empty}>
        <WppTypography type="l-strong">Empty space to avoid scroll jumping</WppTypography>
      </div>
    </>
  )
}
