type Route = {
  url: string
  title: string
}

export const routes: Route[] = [
  { url: '/accordion', title: 'Accordion' },
  { url: '/ag-grid-table-pagination', title: 'AG Grid table - Pagination' },
  { url: '/ag-grid-table-load-more', title: 'AG Grid table - Load More' },
  { url: '/ag-grid-table-infinite-scroll', title: 'AG Grid table - Infinite Scroll' },
  { url: '/ag-grid-table-hybrid-infinite-scroll', title: 'AG Grid table - Hybrid Infinite Scroll' },
  { url: '/autocomplete', title: 'Autocomplete with pills' },
  { url: 'back-to-top-button', title: 'Back To Top Button' },
  { url: '/banners', title: 'Banners' },
  { url: '/chat-input', title: 'ChatInput' },
  { url: 'checkboxes', title: 'Checkboxes' },
  { url: '/colors-generator', title: 'Colors Generator' },
  { url: '/color-picker', title: 'Color Picker' },
  { url: '/datepickers', title: 'Datepickers' },
  { url: '/echarts', title: 'ECharts' },
  { url: '/file-upload', title: 'File Upload' },
  { url: '/form-controls', title: 'Form Controls' },
  { url: '/menu-context', title: 'Menu Context' },
  { url: 'menu-context-based-components', title: 'Menu Context based components' },
  { url: '/modals', title: 'Modals' },
  { url: '/overlay', title: 'Overlay' },
  { url: 'radio-buttons', title: 'Radio Buttons' },
  { url: '/rich-text', title: 'Rich Text' },
  { url: '/search', title: 'Search' },
  { url: '/selects', title: 'Selects' },
  { url: '/single-select', title: 'Single Select' },
  { url: '/multiple-select', title: 'Multiple Select' },
  { url: '/text-select', title: 'Text Select' },
  { url: '/combined-select', title: 'Combined Select' },
  { url: '/skeleton', title: 'Skeleton' },
  { url: '/sticky-bar', title: 'Sticky bar' },
  { url: '/swiper', title: 'Swiper / Carousel' },
  { url: 'toggles', title: 'Toggles' },
  { url: '/topbar', title: 'Topbar' },
  { url: '/time-picker', title: 'Time Picker' },
  { url: '/bugfixes', title: 'Bugfixes' },
  { url: '/performance', title: 'Performance' },
  { url: '/custom-select', title: 'Custom Select' },

  { url: '/vc', title: 'Visual Comparison' },
]

export const VCRoutes: Route[] = [
  { url: 'accordions', title: 'Accordions' },
  { url: 'autocomplete', title: 'Autocomplete' },
  { url: 'avatars', title: 'Avatars' },
  { url: 'breadcrumbs', title: 'Breadcrumbs' },
  { url: 'buttons', title: 'Buttons' },
  { url: 'cards', title: 'Cards' },
  { url: 'card-group', title: 'Card Group' },
  { url: 'checkboxes', title: 'Checkboxes' },
  { url: 'combined-inputs', title: 'Combined Inputs' },
  { url: 'counters', title: 'Counters' },
  { url: 'countries', title: 'Countries' },
  { url: 'datepicker', title: 'Datepicker' },
  { url: 'divider', title: 'Divider' },
  { url: 'expandable-card', title: 'Expandable Card' },
  { url: 'file-upload', title: 'File Upload' },
  { url: 'grid-css', title: 'Grids' },
  { url: 'icons', title: 'Icons' },
  { url: 'images', title: 'Images' },
  { url: 'inline-edit', title: 'Inline Edit' },
  { url: 'inline-messages', title: 'Inline Messages' },
  { url: 'inputs', title: 'Inputs' },
  { url: 'labels', title: 'Labels' },
  { url: 'list-items', title: 'List Items' },
  { url: 'load-more', title: 'Load more' },
  { url: 'menu-context', title: 'Menu Context' },
  { url: 'modals', title: 'Modals' },
  { url: 'nav-sidebar', title: 'Nav Sidebar' },
  { url: 'pagination', title: 'Paginations' },
  { url: 'pills', title: 'Pills' },
  { url: 'popovers', title: 'Popovers' },
  { url: 'progress-indicators', title: 'Progress Indicators' },
  { url: 'radio-buttons', title: 'Radio Buttons' },
  { url: 'search', title: 'Search' },
  { url: 'segmented-controls', title: 'Segmented Controls' },
  { url: 'selects', title: 'Selects' },
  { url: 'selects-multiple', title: 'Selects Multiple' },
  { url: 'selects-single', title: 'Selects Single' },
  { url: 'selects-text', title: 'Selects Text' },
  { url: 'selects-combined', title: 'Selects Combined' },
  { url: 'sliders', title: 'Sliders' },
  { url: 'spinner', title: 'Spinners' },
  { url: 'skeleton', title: 'Skeleton' },
  { url: 'stepper', title: 'Stepper' },
  { url: 'tabs', title: 'Tab Control' },
  { url: 'tags', title: 'Tags' },
  { url: 'text-areas', title: 'Text Areas' },
  { url: 'toasts', title: 'Message Toasts' },
  { url: 'toggles', title: 'Toggles' },
  { url: 'tooltips', title: 'Tooltips' },
  { url: 'topbar', title: 'Topbar' },
  { url: 'tree', title: 'Tree' },
  { url: 'typography', title: 'Typography' },
]

export const BugfixRoutes: Route[] = [
  { url: '4897', title: '(4897) Multiple Components - Auto focus prop' },
  { url: '12842', title: '(12842) Topbar - Dropdown Hidden When Not Visible' },
  { url: '13666', title: '(13666) Popover - Native Events Do not Work' },
  { url: '13719', title: '(13719) Autocomplete - OnBlur' },
  { url: '13723', title: '(13723) List Item - Check Truncation' },
  { url: '14413', title: '(14413) Select - Empty Value' },
  { url: '14506', title: '(14506) Modals - Modal Changes Width/Height With Stepper' },
  { url: '14803', title: '(14803) Select - Dropdown Max Height Css Variable' },
  { url: '15788', title: '(15788) Button - Clicking the disabled button' },
  { url: '15875', title: '(15875) Autofocus - Not Working in Side Modal' },
  { url: '16043', title: '(16043) Datepicker - Locale Formats' },
  { url: '16044', title: '(16044) Multiple Select - Value Set Before Options' },
  { url: '16076', title: '(16076) Select - Focus and Blur events' },
  { url: '16077', title: '(16077) Select - Stateless Component' },
  { url: '16078', title: '(16078) Popover - Interaction with tooltips/dropdowns' },
  { url: '16080', title: '(16080) tippy.js - Components do not work when attached to sortable elements' },
  { url: '16344', title: '(16344) Select - Last item cannot be selected when there is not enough space' },
  { url: '16589', title: '(16589) File Upload - 2+ files with error are uploaded' },
  { url: '16749', title: '(16749) Autocomplete - dropdown does not always display correctly' },
  { url: '17148', title: '(17148) Modals - issue with overflow: hidden' },
  { url: '18403', title: '(18403) Multiple Select issue with disabled item' },
  { url: '18849', title: '(18849) Text Select 2 lines' },
  { url: '19108', title: '(19108) Event not triggering on MenuContext with ListItem' },
  { url: '20537', title: '(20537) Autocomplete - problems with createNewElement button' },
  { url: '21215', title: '(21215) Dropdown Gets cropped by parent' },
  { url: '22987', title: '(22987) S size components have wrong heights' },
  { url: '23062', title: '(23062) Segmented Control - Single Item Fix' },
  { url: '25809', title: '(25809) Add dynamic width support to WppTree' },
  { url: '26380', title: '(26380) Slider - Fix slider marks in Side Modal' },
  { url: '27272', title: '(27272) Slider - Click selection not working properly' },
  { url: '27305', title: '(27305) Slider - Input validations' },
  { url: '27379', title: '(27379) Slider - Marks do not appear on slider' },
  { url: '27483', title: '(27483) Datepicker - dependable datepickers issue for different formats' },
  { url: '29773', title: '(29773) Card Group - Allow no card selected by default' },
  { url: '29829', title: '(29829) Card Group - Nested cards are selectable' },
  { url: '29098', title: '(29098) Select - value of items cannot be falsy' },
  { url: '30026', title: '(30026) Stepper - Resize Observer issue' },
  { url: '28186', title: '(28186) Slider - Label Overlap Issue' },
  { url: '30643', title: '(30643) Popover - Clicking non-interactive elements issue' },
  { url: '30741', title: '(30741) SideModal - Opening side-modal through a ref does not remove the scrollbar' },
  { url: '30768', title: '(30768) Dropdowns - not rendered correctly in DOM' },
  { url: '31351', title: '(31351) Selects - Dependable selects issue' },
  { url: '30901', title: '(30901) Button ActionButton FloatingButton - Enter key triggers onClick event' },
  { url: '27613', title: '(27613) Input: Input Field and Tooltip Issue' },
  { url: '31258', title: '(31258) Stepper - Dynamic content not truncated' },
  { url: '29273', title: '(29273) Richtext - Editor link tooltip hidden' },
  { url: '31688', title: '(31688) Selects - Multi child dependency selects issue' },
  { url: '31702', title: '(31702) Button ActionButton FloatingButton - Fix onClick events for Button loading state' },
  { url: '31510', title: '(31510) Card group - items not selected after changing children' },
  { url: '31410', title: '(31410) Sidebar - multiple placement issues' },
  { url: '31906', title: '(31906) Typography - Italic style causes the last character to clip' },
  { url: '31910', title: '(31910) Inline Edit - Support more flexible CSS expressions into InputWidth prop' },
  { url: '31855', title: '(31855) Search - items not displayed when loading API data with caching' },
  { url: '32186', title: '(32186) Modals - issues with events' },
  { url: '32121', title: '(32121) Card Group - added checks for card children' },
  { url: '54', title: '(54) Button - Icon color not updated for destructive-secondary disabled button variant' },
  { url: '32255', title: '(32255) File Upload - Fix for Empty acceptConfig' },
  { url: '161', title: '(161) Tooltip - misaligned when text changes dynamically' },
  { url: '48', title: '(48) Input - tooltip does not appear when text truncated in some cases' },
  { url: '310', title: '(310) Inline Edit - several issues with component' },
  { url: '326', title: '(326) Input - new event which emits both raw and formatted value' },
  { url: '516', title: '(516) Card Group - issue when nesting card group inside a card' },
  { url: '296', title: '(296) List Item - validate list item slots' },
  { url: '496', title: '(496) Autocomplete button placement' },
  { url: '543', title: '(543) Richtext Markdown Fix' },
  { url: '574', title: '(574) Multiple select - multiple issues' },
  { url: '676', title: '(676) Re-calculate tooltip label in WppListItem component' },
]

export const PerfRoutes: Route[] = [
  { url: 'autocompletes', title: 'Autocompletes' },
  { url: 'selects', title: 'Selects' },
]
