const ONE_PIXEL_TRANSPARENT_GIF = 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7';
const LIB_COMPONENTS_PREFIX = 'wpp-';

export { LIB_COMPONENTS_PREFIX as L, ONE_PIXEL_TRANSPARENT_GIF as O };
