const MENU_BAR_ROLE = 'menubar';
const MENU_CONTEXT_TAG = 'WPP-MENU-CONTEXT';
const CONTEXT_ITEM_TAG = 'WPP-LIST-ITEM';
const BUTTON_ROLE = 'button';
const TOPBAR_NAVIGATION_ITEM_TAG = 'WPP-NAVIGATION-ITEM';
const MENU_ROLE = 'menu';
const MENU_ITEM = 'menuitem';
const GROUP_ROLE = 'group';
const PRESENTATION_ROLE = 'presentation';
const WPP_LIST_CLASSNAME = 'wpp-list';
const TAB_FOCUS_CLASS = 'tab-focus';
const MENU_CONTEXT_KEYBOARD_ACTIVATION_EVENT = 'wppMenuContextKeyboardActivation';

export { BUTTON_ROLE as B, CONTEXT_ITEM_TAG as C, GROUP_ROLE as G, MENU_ROLE as M, PRESENTATION_ROLE as P, TAB_FOCUS_CLASS as T, WPP_LIST_CLASSNAME as W, MENU_ITEM as a, MENU_CONTEXT_TAG as b, TOPBAR_NAVIGATION_ITEM_TAG as c, MENU_CONTEXT_KEYBOARD_ACTIVATION_EVENT as d, MENU_BAR_ROLE as e };
