export { getAssetPath, setAssetPath, setNonce, setPlatformOptions } from '@stencil/core/internal/client';
export { Z as Z_INDEX } from './consts.js';
import { i as isObject, t as toKebabCase, r as recursiveObjectMap } from './utils.js';
export { m as applyBodyStylesIfNeeded, a as areSetsEqual, n as autoFocusElement, l as closestElement, d as debounce, o as form2object, f as format, y as getAriaProps, p as getDurationValues, q as getHasFocused, w as getHighestContainerInDOM, j as getHighlightData, x as getOsBarOffsetHeight, g as getSlotEmptyStates, c as hasParentWithId, h as hasShadowDom, b as isEventTargetContained, i as isObject, z as isWppElement, r as recursiveObjectMap, s as selectDropdownWidth, v as setHasFocused, t as toKebabCase, k as transformToVersionedTag, e as truncate, u as uuidv4 } from './utils.js';
export { S as ScrollState, WppFileUpload, defineCustomElement as defineCustomElementWppFileUpload } from './wpp-file-upload.js';
export { F as FullScreenModalCloseReason, WppFullScreenModal, defineCustomElement as defineCustomElementWppFullScreenModal } from './wpp-full-screen-modal.js';
export { I as InlineEditModeEnum, WppInlineEdit, defineCustomElement as defineCustomElementWppInlineEdit } from './wpp-inline-edit.js';
export { M as ModalCloseReason, WppModal, defineCustomElement as defineCustomElementWppModal } from './wpp-modal.js';
export { E as Editor, Q as Quill, U as RICHTEXT_UPLOAD_REQUEST_EVENT, d as debugLevels, f as formats, u as richtextUploadTypes, s as sources } from './tiptap-config.js';
export { T as TIPTAP_UPLOAD_REQUEST_EVENT, WppRichtext, defineCustomElement as defineCustomElementWppRichtext, a as tiptapFormats, b as tiptapSources, t as tiptapUploadTypes } from './wpp-richtext.js';
export { S as SideModalCloseReason, WppSideModal, defineCustomElement as defineCustomElementWppSideModal } from './wpp-side-modal.js';
export { WppAccordion, defineCustomElement as defineCustomElementWppAccordion } from './wpp-accordion.js';
export { WppActionButton, defineCustomElement as defineCustomElementWppActionButton } from './wpp-action-button.js';
export { WppArtefact, defineCustomElement as defineCustomElementWppArtefact } from './wpp-artefact.js';
export { WppAutocomplete, defineCustomElement as defineCustomElementWppAutocomplete } from './wpp-autocomplete.js';
export { WppAvatar, defineCustomElement as defineCustomElementWppAvatar } from './wpp-avatar.js';
export { WppAvatarGroup, defineCustomElement as defineCustomElementWppAvatarGroup } from './wpp-avatar-group.js';
export { WppBackToTopButton, defineCustomElement as defineCustomElementWppBackToTopButton } from './wpp-back-to-top-button.js';
export { WppBanner, defineCustomElement as defineCustomElementWppBanner } from './wpp-banner.js';
export { WppBasicNode, defineCustomElement as defineCustomElementWppBasicNode } from './wpp-basic-node.js';
export { WppBreadcrumb, defineCustomElement as defineCustomElementWppBreadcrumb } from './wpp-breadcrumb.js';
export { WppButton, defineCustomElement as defineCustomElementWppButton } from './wpp-button.js';
export { WppCard, defineCustomElement as defineCustomElementWppCard } from './wpp-card.js';
export { WppCardGroup, defineCustomElement as defineCustomElementWppCardGroup } from './wpp-card-group.js';
export { WppChatConversation, defineCustomElement as defineCustomElementWppChatConversation } from './wpp-chat-conversation.js';
export { WppChatConversationMessage, defineCustomElement as defineCustomElementWppChatConversationMessage } from './wpp-chat-conversation-message.js';
export { WppChatInput, defineCustomElement as defineCustomElementWppChatInput } from './wpp-chat-input.js';
export { WppChatNode, defineCustomElement as defineCustomElementWppChatNode } from './wpp-chat-node.js';
export { WppCheckbox, defineCustomElement as defineCustomElementWppCheckbox } from './wpp-checkbox.js';
export { WppCheckboxGroup, defineCustomElement as defineCustomElementWppCheckboxGroup } from './wpp-checkbox-group.js';
export { WppColorPicker, defineCustomElement as defineCustomElementWppColorPicker } from './wpp-color-picker.js';
export { WppCounter, defineCustomElement as defineCustomElementWppCounter } from './wpp-counter.js';
export { WppDatepicker, defineCustomElement as defineCustomElementWppDatepicker } from './wpp-datepicker.js';
export { WppDivider, defineCustomElement as defineCustomElementWppDivider } from './wpp-divider.js';
export { WppEmpty404, defineCustomElement as defineCustomElementWppEmpty404 } from './wpp-empty-404.js';
export { WppEmptyCards, defineCustomElement as defineCustomElementWppEmptyCards } from './wpp-empty-cards.js';
export { WppEmptyContent, defineCustomElement as defineCustomElementWppEmptyContent } from './wpp-empty-content.js';
export { WppEmptyDataviz, defineCustomElement as defineCustomElementWppEmptyDataviz } from './wpp-empty-dataviz.js';
export { WppEmptyDowntime, defineCustomElement as defineCustomElementWppEmptyDowntime } from './wpp-empty-downtime.js';
export { WppEmptyError, defineCustomElement as defineCustomElementWppEmptyError } from './wpp-empty-error.js';
export { WppEmptyFolder, defineCustomElement as defineCustomElementWppEmptyFolder } from './wpp-empty-folder.js';
export { WppEmptyNoAccess, defineCustomElement as defineCustomElementWppEmptyNoAccess } from './wpp-empty-no-access.js';
export { WppEmptyNoConnection, defineCustomElement as defineCustomElementWppEmptyNoConnection } from './wpp-empty-no-connection.js';
export { WppEmptyNothingFound, defineCustomElement as defineCustomElementWppEmptyNothingFound } from './wpp-empty-nothing-found.js';
export { WppEmptyNotifications, defineCustomElement as defineCustomElementWppEmptyNotifications } from './wpp-empty-notifications.js';
export { WppEmptyTable, defineCustomElement as defineCustomElementWppEmptyTable } from './wpp-empty-table.js';
export { WppExpandableCard, defineCustomElement as defineCustomElementWppExpandableCard } from './wpp-expandable-card.js';
export { WppFileUploadItem, defineCustomElement as defineCustomElementWppFileUploadItem } from './wpp-file-upload-item.js';
export { WppFilterButton, defineCustomElement as defineCustomElementWppFilterButton } from './wpp-filter-button.js';
export { WppFloatingButton, defineCustomElement as defineCustomElementWppFloatingButton } from './wpp-floating-button.js';
export { WppFloatingToolbar, defineCustomElement as defineCustomElementWppFloatingToolbar } from './wpp-floating-toolbar.js';
export { WppGrid, defineCustomElement as defineCustomElementWppGrid } from './wpp-grid.js';
export { WppHandle, defineCustomElement as defineCustomElementWppHandle } from './wpp-handle.js';
export { WppHueSlider, defineCustomElement as defineCustomElementWppHueSlider } from './wpp-hue-slider.js';
export { WppIconAbout, defineCustomElement as defineCustomElementWppIconAbout } from './wpp-icon-about.js';
export { WppIconAccessibility, defineCustomElement as defineCustomElementWppIconAccessibility } from './wpp-icon-accessibility.js';
export { WppIconAccordion, defineCustomElement as defineCustomElementWppIconAccordion } from './wpp-icon-accordion.js';
export { WppIconAction, defineCustomElement as defineCustomElementWppIconAction } from './wpp-icon-action.js';
export { WppIconAdd, defineCustomElement as defineCustomElementWppIconAdd } from './wpp-icon-add.js';
export { WppIconAddApp, defineCustomElement as defineCustomElementWppIconAddApp } from './wpp-icon-add-app.js';
export { WppIconAddCircle, defineCustomElement as defineCustomElementWppIconAddCircle } from './wpp-icon-add-circle.js';
export { WppIconAddDocument, defineCustomElement as defineCustomElementWppIconAddDocument } from './wpp-icon-add-document.js';
export { WppIconAddFolder, defineCustomElement as defineCustomElementWppIconAddFolder } from './wpp-icon-add-folder.js';
export { WppIconAdmin, defineCustomElement as defineCustomElementWppIconAdmin } from './wpp-icon-admin.js';
export { WppIconAi, defineCustomElement as defineCustomElementWppIconAi } from './wpp-icon-ai.js';
export { WppIconAirPollution, defineCustomElement as defineCustomElementWppIconAirPollution } from './wpp-icon-air-pollution.js';
export { WppIconAirplane, defineCustomElement as defineCustomElementWppIconAirplane } from './wpp-icon-airplane.js';
export { WppIconAngry, defineCustomElement as defineCustomElementWppIconAngry } from './wpp-icon-angry.js';
export { WppIconApp, defineCustomElement as defineCustomElementWppIconApp } from './wpp-icon-app.js';
export { WppIconAppFolder, defineCustomElement as defineCustomElementWppIconAppFolder } from './wpp-icon-app-folder.js';
export { WppIconAppStore, defineCustomElement as defineCustomElementWppIconAppStore } from './wpp-icon-app-store.js';
export { WppIconApprovals, defineCustomElement as defineCustomElementWppIconApprovals } from './wpp-icon-approvals.js';
export { WppIconArchive, defineCustomElement as defineCustomElementWppIconArchive } from './wpp-icon-archive.js';
export { WppIconArchiveMultiple, defineCustomElement as defineCustomElementWppIconArchiveMultiple } from './wpp-icon-archive-multiple.js';
export { WppIconArrow, defineCustomElement as defineCustomElementWppIconArrow } from './wpp-icon-arrow.js';
export { WppIconAsk, defineCustomElement as defineCustomElementWppIconAsk } from './wpp-icon-ask.js';
export { WppIconAssistant, defineCustomElement as defineCustomElementWppIconAssistant } from './wpp-icon-assistant.js';
export { WppIconAtm, defineCustomElement as defineCustomElementWppIconAtm } from './wpp-icon-atm.js';
export { WppIconAttach, defineCustomElement as defineCustomElementWppIconAttach } from './wpp-icon-attach.js';
export { WppIconAutoSum, defineCustomElement as defineCustomElementWppIconAutoSum } from './wpp-icon-auto-sum.js';
export { WppIconAutofit, defineCustomElement as defineCustomElementWppIconAutofit } from './wpp-icon-autofit.js';
export { WppIconAutofitHeight, defineCustomElement as defineCustomElementWppIconAutofitHeight } from './wpp-icon-autofit-height.js';
export { WppIconAutofitHeightDotted, defineCustomElement as defineCustomElementWppIconAutofitHeightDotted } from './wpp-icon-autofit-height-dotted.js';
export { WppIconAutofitWidth, defineCustomElement as defineCustomElementWppIconAutofitWidth } from './wpp-icon-autofit-width.js';
export { WppIconAutofitWidthDotted, defineCustomElement as defineCustomElementWppIconAutofitWidthDotted } from './wpp-icon-autofit-width-dotted.js';
export { WppIconAvailableCheckmark, defineCustomElement as defineCustomElementWppIconAvailableCheckmark } from './wpp-icon-available-checkmark.js';
export { WppIconAvailableUpdate, defineCustomElement as defineCustomElementWppIconAvailableUpdate } from './wpp-icon-available-update.js';
export { WppIconBank, defineCustomElement as defineCustomElementWppIconBank } from './wpp-icon-bank.js';
export { WppIconBar, defineCustomElement as defineCustomElementWppIconBar } from './wpp-icon-bar.js';
export { WppIconBarChart, defineCustomElement as defineCustomElementWppIconBarChart } from './wpp-icon-bar-chart.js';
export { WppIconBarHorizontal, defineCustomElement as defineCustomElementWppIconBarHorizontal } from './wpp-icon-bar-horizontal.js';
export { WppIconBicycle, defineCustomElement as defineCustomElementWppIconBicycle } from './wpp-icon-bicycle.js';
export { WppIconBlockquote, defineCustomElement as defineCustomElementWppIconBlockquote } from './wpp-icon-blockquote.js';
export { WppIconBluetoothOff, defineCustomElement as defineCustomElementWppIconBluetoothOff } from './wpp-icon-bluetooth-off.js';
export { WppIconBluetoothOn, defineCustomElement as defineCustomElementWppIconBluetoothOn } from './wpp-icon-bluetooth-on.js';
export { WppIconBoard, defineCustomElement as defineCustomElementWppIconBoard } from './wpp-icon-board.js';
export { WppIconBold, defineCustomElement as defineCustomElementWppIconBold } from './wpp-icon-bold.js';
export { WppIconBook, defineCustomElement as defineCustomElementWppIconBook } from './wpp-icon-book.js';
export { WppIconBookContacts, defineCustomElement as defineCustomElementWppIconBookContacts } from './wpp-icon-book-contacts.js';
export { WppIconBookFaq, defineCustomElement as defineCustomElementWppIconBookFaq } from './wpp-icon-book-faq.js';
export { WppIconBookInformation, defineCustomElement as defineCustomElementWppIconBookInformation } from './wpp-icon-book-information.js';
export { WppIconBookSearch, defineCustomElement as defineCustomElementWppIconBookSearch } from './wpp-icon-book-search.js';
export { WppIconBookmark, defineCustomElement as defineCustomElementWppIconBookmark } from './wpp-icon-bookmark.js';
export { WppIconBookmarkAdd, defineCustomElement as defineCustomElementWppIconBookmarkAdd } from './wpp-icon-bookmark-add.js';
export { WppIconBookmarkSelected, defineCustomElement as defineCustomElementWppIconBookmarkSelected } from './wpp-icon-bookmark-selected.js';
export { WppIconBorder, defineCustomElement as defineCustomElementWppIconBorder } from './wpp-icon-border.js';
export { WppIconBorderAll, defineCustomElement as defineCustomElementWppIconBorderAll } from './wpp-icon-border-all.js';
export { WppIconBorderBottomDouble, defineCustomElement as defineCustomElementWppIconBorderBottomDouble } from './wpp-icon-border-bottom-double.js';
export { WppIconBorderLeftRight, defineCustomElement as defineCustomElementWppIconBorderLeftRight } from './wpp-icon-border-left-right.js';
export { WppIconBorderNone, defineCustomElement as defineCustomElementWppIconBorderNone } from './wpp-icon-border-none.js';
export { WppIconBorderOutside, defineCustomElement as defineCustomElementWppIconBorderOutside } from './wpp-icon-border-outside.js';
export { WppIconBorderOutsideThick, defineCustomElement as defineCustomElementWppIconBorderOutsideThick } from './wpp-icon-border-outside-thick.js';
export { WppIconBorderTopBottom, defineCustomElement as defineCustomElementWppIconBorderTopBottom } from './wpp-icon-border-top-bottom.js';
export { WppIconBorderTopBottomDouble, defineCustomElement as defineCustomElementWppIconBorderTopBottomDouble } from './wpp-icon-border-top-bottom-double.js';
export { WppIconBorderTopBottomThick, defineCustomElement as defineCustomElementWppIconBorderTopBottomThick } from './wpp-icon-border-top-bottom-thick.js';
export { WppIconBot, defineCustomElement as defineCustomElementWppIconBot } from './wpp-icon-bot.js';
export { WppIconBounce, defineCustomElement as defineCustomElementWppIconBounce } from './wpp-icon-bounce.js';
export { WppIconBranch, defineCustomElement as defineCustomElementWppIconBranch } from './wpp-icon-branch.js';
export { WppIconBranchRequest, defineCustomElement as defineCustomElementWppIconBranchRequest } from './wpp-icon-branch-request.js';
export { WppIconBranchReview, defineCustomElement as defineCustomElementWppIconBranchReview } from './wpp-icon-branch-review.js';
export { WppIconBtc, defineCustomElement as defineCustomElementWppIconBtc } from './wpp-icon-btc.js';
export { WppIconBus, defineCustomElement as defineCustomElementWppIconBus } from './wpp-icon-bus.js';
export { WppIconBusiness, defineCustomElement as defineCustomElementWppIconBusiness } from './wpp-icon-business.js';
export { WppIconCafe, defineCustomElement as defineCustomElementWppIconCafe } from './wpp-icon-cafe.js';
export { WppIconCalendar, defineCustomElement as defineCustomElementWppIconCalendar } from './wpp-icon-calendar.js';
export { WppIconCalendar3Days, defineCustomElement as defineCustomElementWppIconCalendar3Days } from './wpp-icon-calendar-3-days.js';
export { WppIconCalendarAdd, defineCustomElement as defineCustomElementWppIconCalendarAdd } from './wpp-icon-calendar-add.js';
export { WppIconCalendarDate, defineCustomElement as defineCustomElementWppIconCalendarDate } from './wpp-icon-calendar-date.js';
export { WppIconCalendarDismiss, defineCustomElement as defineCustomElementWppIconCalendarDismiss } from './wpp-icon-calendar-dismiss.js';
export { WppIconCalendarError, defineCustomElement as defineCustomElementWppIconCalendarError } from './wpp-icon-calendar-error.js';
export { WppIconCalendarMonth, defineCustomElement as defineCustomElementWppIconCalendarMonth } from './wpp-icon-calendar-month.js';
export { WppIconCameraAdd, defineCustomElement as defineCustomElementWppIconCameraAdd } from './wpp-icon-camera-add.js';
export { WppIconCameraOff, defineCustomElement as defineCustomElementWppIconCameraOff } from './wpp-icon-camera-off.js';
export { WppIconCameraOn, defineCustomElement as defineCustomElementWppIconCameraOn } from './wpp-icon-camera-on.js';
export { WppIconCameraSwitch, defineCustomElement as defineCustomElementWppIconCameraSwitch } from './wpp-icon-camera-switch.js';
export { WppIconCampaign, defineCustomElement as defineCustomElementWppIconCampaign } from './wpp-icon-campaign.js';
export { WppIconCaptionOff, defineCustomElement as defineCustomElementWppIconCaptionOff } from './wpp-icon-caption-off.js';
export { WppIconCaptionOn, defineCustomElement as defineCustomElementWppIconCaptionOn } from './wpp-icon-caption-on.js';
export { WppIconCarousel, defineCustomElement as defineCustomElementWppIconCarousel } from './wpp-icon-carousel.js';
export { WppIconCart, defineCustomElement as defineCustomElementWppIconCart } from './wpp-icon-cart.js';
export { WppIconCase, defineCustomElement as defineCustomElementWppIconCase } from './wpp-icon-case.js';
export { WppIconCast, defineCustomElement as defineCustomElementWppIconCast } from './wpp-icon-cast.js';
export { WppIconCellularData3g, defineCustomElement as defineCustomElementWppIconCellularData3g } from './wpp-icon-cellular-data-3g.js';
export { WppIconCellularData4g, defineCustomElement as defineCustomElementWppIconCellularData4g } from './wpp-icon-cellular-data-4g.js';
export { WppIconCellularData5g, defineCustomElement as defineCustomElementWppIconCellularData5g } from './wpp-icon-cellular-data-5g.js';
export { WppIconCellularDataOff, defineCustomElement as defineCustomElementWppIconCellularDataOff } from './wpp-icon-cellular-data-off.js';
export { WppIconCellularDataOn, defineCustomElement as defineCustomElementWppIconCellularDataOn } from './wpp-icon-cellular-data-on.js';
export { WppIconChannel, defineCustomElement as defineCustomElementWppIconChannel } from './wpp-icon-channel.js';
export { WppIconChatMessage, defineCustomElement as defineCustomElementWppIconChatMessage } from './wpp-icon-chat-message.js';
export { WppIconChatMessageNew, defineCustomElement as defineCustomElementWppIconChatMessageNew } from './wpp-icon-chat-message-new.js';
export { WppIconChatMessageOff, defineCustomElement as defineCustomElementWppIconChatMessageOff } from './wpp-icon-chat-message-off.js';
export { WppIconChatVideo, defineCustomElement as defineCustomElementWppIconChatVideo } from './wpp-icon-chat-video.js';
export { WppIconChevron, defineCustomElement as defineCustomElementWppIconChevron } from './wpp-icon-chevron.js';
export { WppIconCinema, defineCustomElement as defineCustomElementWppIconCinema } from './wpp-icon-cinema.js';
export { WppIconCircle, defineCustomElement as defineCustomElementWppIconCircle } from './wpp-icon-circle.js';
export { WppIconClock, defineCustomElement as defineCustomElementWppIconClock } from './wpp-icon-clock.js';
export { WppIconClose, defineCustomElement as defineCustomElementWppIconClose } from './wpp-icon-close.js';
export { WppIconCloudDismiss, defineCustomElement as defineCustomElementWppIconCloudDismiss } from './wpp-icon-cloud-dismiss.js';
export { WppIconCloudSuccess, defineCustomElement as defineCustomElementWppIconCloudSuccess } from './wpp-icon-cloud-success.js';
export { WppIconCloudSync, defineCustomElement as defineCustomElementWppIconCloudSync } from './wpp-icon-cloud-sync.js';
export { WppIconCloudUpload, defineCustomElement as defineCustomElementWppIconCloudUpload } from './wpp-icon-cloud-upload.js';
export { WppIconCodeView, defineCustomElement as defineCustomElementWppIconCodeView } from './wpp-icon-code-view.js';
export { WppIconCollapse, defineCustomElement as defineCustomElementWppIconCollapse } from './wpp-icon-collapse.js';
export { WppIconCollection, defineCustomElement as defineCustomElementWppIconCollection } from './wpp-icon-collection.js';
export { WppIconColour, defineCustomElement as defineCustomElementWppIconColour } from './wpp-icon-colour.js';
export { WppIconColumnsOne, defineCustomElement as defineCustomElementWppIconColumnsOne } from './wpp-icon-columns-one.js';
export { WppIconColumnsThree, defineCustomElement as defineCustomElementWppIconColumnsThree } from './wpp-icon-columns-three.js';
export { WppIconColumnsTwo, defineCustomElement as defineCustomElementWppIconColumnsTwo } from './wpp-icon-columns-two.js';
export { WppIconComment, defineCustomElement as defineCustomElementWppIconComment } from './wpp-icon-comment.js';
export { WppIconCommentOff, defineCustomElement as defineCustomElementWppIconCommentOff } from './wpp-icon-comment-off.js';
export { WppIconCommunication, defineCustomElement as defineCustomElementWppIconCommunication } from './wpp-icon-communication.js';
export { WppIconCompose, defineCustomElement as defineCustomElementWppIconCompose } from './wpp-icon-compose.js';
export { WppIconCookies, defineCustomElement as defineCustomElementWppIconCookies } from './wpp-icon-cookies.js';
export { WppIconCopy, defineCustomElement as defineCustomElementWppIconCopy } from './wpp-icon-copy.js';
export { WppIconCrop, defineCustomElement as defineCustomElementWppIconCrop } from './wpp-icon-crop.js';
export { WppIconCross, defineCustomElement as defineCustomElementWppIconCross } from './wpp-icon-cross.js';
export { WppIconCta, defineCustomElement as defineCustomElementWppIconCta } from './wpp-icon-cta.js';
export { WppIconCube, defineCustomElement as defineCustomElementWppIconCube } from './wpp-icon-cube.js';
export { WppIconCurrency, defineCustomElement as defineCustomElementWppIconCurrency } from './wpp-icon-currency.js';
export { WppIconCut, defineCustomElement as defineCustomElementWppIconCut } from './wpp-icon-cut.js';
export { WppIconDarkTheme, defineCustomElement as defineCustomElementWppIconDarkTheme } from './wpp-icon-dark-theme.js';
export { WppIconDash, defineCustomElement as defineCustomElementWppIconDash } from './wpp-icon-dash.js';
export { WppIconDataArea, defineCustomElement as defineCustomElementWppIconDataArea } from './wpp-icon-data-area.js';
export { WppIconDataCloudOff, defineCustomElement as defineCustomElementWppIconDataCloudOff } from './wpp-icon-data-cloud-off.js';
export { WppIconDataCloudOn, defineCustomElement as defineCustomElementWppIconDataCloudOn } from './wpp-icon-data-cloud-on.js';
export { WppIconDataFunnel, defineCustomElement as defineCustomElementWppIconDataFunnel } from './wpp-icon-data-funnel.js';
export { WppIconDataHistogram, defineCustomElement as defineCustomElementWppIconDataHistogram } from './wpp-icon-data-histogram.js';
export { WppIconDataLine, defineCustomElement as defineCustomElementWppIconDataLine } from './wpp-icon-data-line.js';
export { WppIconDataScatter, defineCustomElement as defineCustomElementWppIconDataScatter } from './wpp-icon-data-scatter.js';
export { WppIconDataSunburst, defineCustomElement as defineCustomElementWppIconDataSunburst } from './wpp-icon-data-sunburst.js';
export { WppIconDataTransfer, defineCustomElement as defineCustomElementWppIconDataTransfer } from './wpp-icon-data-transfer.js';
export { WppIconDataTreemap, defineCustomElement as defineCustomElementWppIconDataTreemap } from './wpp-icon-data-treemap.js';
export { WppIconDataTrending, defineCustomElement as defineCustomElementWppIconDataTrending } from './wpp-icon-data-trending.js';
export { WppIconDataUsage, defineCustomElement as defineCustomElementWppIconDataUsage } from './wpp-icon-data-usage.js';
export { WppIconDataViewCards, defineCustomElement as defineCustomElementWppIconDataViewCards } from './wpp-icon-data-view-cards.js';
export { WppIconDataViewList, defineCustomElement as defineCustomElementWppIconDataViewList } from './wpp-icon-data-view-list.js';
export { WppIconDataWaterfall, defineCustomElement as defineCustomElementWppIconDataWaterfall } from './wpp-icon-data-waterfall.js';
export { WppIconDataWhisker, defineCustomElement as defineCustomElementWppIconDataWhisker } from './wpp-icon-data-whisker.js';
export { WppIconDatabase, defineCustomElement as defineCustomElementWppIconDatabase } from './wpp-icon-database.js';
export { WppIconDecrease, defineCustomElement as defineCustomElementWppIconDecrease } from './wpp-icon-decrease.js';
export { WppIconDesign, defineCustomElement as defineCustomElementWppIconDesign } from './wpp-icon-design.js';
export { WppIconDesktop, defineCustomElement as defineCustomElementWppIconDesktop } from './wpp-icon-desktop.js';
export { WppIconDiamond, defineCustomElement as defineCustomElementWppIconDiamond } from './wpp-icon-diamond.js';
export { WppIconDirections, defineCustomElement as defineCustomElementWppIconDirections } from './wpp-icon-directions.js';
export { WppIconDiversity, defineCustomElement as defineCustomElementWppIconDiversity } from './wpp-icon-diversity.js';
export { WppIconDocument, defineCustomElement as defineCustomElementWppIconDocument } from './wpp-icon-document.js';
export { WppIconDocumentBlocked, defineCustomElement as defineCustomElementWppIconDocumentBlocked } from './wpp-icon-document-blocked.js';
export { WppIconDocumentError, defineCustomElement as defineCustomElementWppIconDocumentError } from './wpp-icon-document-error.js';
export { WppIconDollar, defineCustomElement as defineCustomElementWppIconDollar } from './wpp-icon-dollar.js';
export { WppIconDone, defineCustomElement as defineCustomElementWppIconDone } from './wpp-icon-done.js';
export { WppIconDoubleChevron, defineCustomElement as defineCustomElementWppIconDoubleChevron } from './wpp-icon-double-chevron.js';
export { WppIconDownload, defineCustomElement as defineCustomElementWppIconDownload } from './wpp-icon-download.js';
export { WppIconDraft, defineCustomElement as defineCustomElementWppIconDraft } from './wpp-icon-draft.js';
export { WppIconDrag, defineCustomElement as defineCustomElementWppIconDrag } from './wpp-icon-drag.js';
export { WppIconDragAndDrop, defineCustomElement as defineCustomElementWppIconDragAndDrop } from './wpp-icon-drag-and-drop.js';
export { WppIconEco, defineCustomElement as defineCustomElementWppIconEco } from './wpp-icon-eco.js';
export { WppIconEdit, defineCustomElement as defineCustomElementWppIconEdit } from './wpp-icon-edit.js';
export { WppIconEditText, defineCustomElement as defineCustomElementWppIconEditText } from './wpp-icon-edit-text.js';
export { WppIconEditorLowercase, defineCustomElement as defineCustomElementWppIconEditorLowercase } from './wpp-icon-editor-lowercase.js';
export { WppIconEditorObjectAlignmentCenter, defineCustomElement as defineCustomElementWppIconEditorObjectAlignmentCenter } from './wpp-icon-editor-object-alignment-center.js';
export { WppIconEditorTitle, defineCustomElement as defineCustomElementWppIconEditorTitle } from './wpp-icon-editor-title.js';
export { WppIconEditorUppercase, defineCustomElement as defineCustomElementWppIconEditorUppercase } from './wpp-icon-editor-uppercase.js';
export { WppIconEffects, defineCustomElement as defineCustomElementWppIconEffects } from './wpp-icon-effects.js';
export { WppIconEnlarge, defineCustomElement as defineCustomElementWppIconEnlarge } from './wpp-icon-enlarge.js';
export { WppIconEnter, defineCustomElement as defineCustomElementWppIconEnter } from './wpp-icon-enter.js';
export { WppIconEraser, defineCustomElement as defineCustomElementWppIconEraser } from './wpp-icon-eraser.js';
export { WppIconError, defineCustomElement as defineCustomElementWppIconError } from './wpp-icon-error.js';
export { WppIconEth, defineCustomElement as defineCustomElementWppIconEth } from './wpp-icon-eth.js';
export { WppIconEuro, defineCustomElement as defineCustomElementWppIconEuro } from './wpp-icon-euro.js';
export { WppIconEvent, defineCustomElement as defineCustomElementWppIconEvent } from './wpp-icon-event.js';
export { WppIconExpand, defineCustomElement as defineCustomElementWppIconExpand } from './wpp-icon-expand.js';
export { WppIconExperiment, defineCustomElement as defineCustomElementWppIconExperiment } from './wpp-icon-experiment.js';
export { WppIconExport, defineCustomElement as defineCustomElementWppIconExport } from './wpp-icon-export.js';
export { WppIconExportFile, defineCustomElement as defineCustomElementWppIconExportFile } from './wpp-icon-export-file.js';
export { WppIconExtension, defineCustomElement as defineCustomElementWppIconExtension } from './wpp-icon-extension.js';
export { WppIconExternalLink, defineCustomElement as defineCustomElementWppIconExternalLink } from './wpp-icon-external-link.js';
export { WppIconEyeOff, defineCustomElement as defineCustomElementWppIconEyeOff } from './wpp-icon-eye-off.js';
export { WppIconEyeOn, defineCustomElement as defineCustomElementWppIconEyeOn } from './wpp-icon-eye-on.js';
export { WppIconEyedropper, defineCustomElement as defineCustomElementWppIconEyedropper } from './wpp-icon-eyedropper.js';
export { WppIconFactory, defineCustomElement as defineCustomElementWppIconFactory } from './wpp-icon-factory.js';
export { WppIconFavourites, defineCustomElement as defineCustomElementWppIconFavourites } from './wpp-icon-favourites.js';
export { WppIconFavouritesFilled, defineCustomElement as defineCustomElementWppIconFavouritesFilled } from './wpp-icon-favourites-filled.js';
export { WppIconFile, defineCustomElement as defineCustomElementWppIconFile } from './wpp-icon-file.js';
export { WppIconFileCss, defineCustomElement as defineCustomElementWppIconFileCss } from './wpp-icon-file-css.js';
export { WppIconFileJs, defineCustomElement as defineCustomElementWppIconFileJs } from './wpp-icon-file-js.js';
export { WppIconFilePdf, defineCustomElement as defineCustomElementWppIconFilePdf } from './wpp-icon-file-pdf.js';
export { WppIconFileZip, defineCustomElement as defineCustomElementWppIconFileZip } from './wpp-icon-file-zip.js';
export { WppIconFill, defineCustomElement as defineCustomElementWppIconFill } from './wpp-icon-fill.js';
export { WppIconFilter, defineCustomElement as defineCustomElementWppIconFilter } from './wpp-icon-filter.js';
export { WppIconFingerprint, defineCustomElement as defineCustomElementWppIconFingerprint } from './wpp-icon-fingerprint.js';
export { WppIconFitHeight, defineCustomElement as defineCustomElementWppIconFitHeight } from './wpp-icon-fit-height.js';
export { WppIconFitWidth, defineCustomElement as defineCustomElementWppIconFitWidth } from './wpp-icon-fit-width.js';
export { WppIconFlagOff, defineCustomElement as defineCustomElementWppIconFlagOff } from './wpp-icon-flag-off.js';
export { WppIconFlagOn, defineCustomElement as defineCustomElementWppIconFlagOn } from './wpp-icon-flag-on.js';
export { WppIconFlip, defineCustomElement as defineCustomElementWppIconFlip } from './wpp-icon-flip.js';
export { WppIconFloatCenter, defineCustomElement as defineCustomElementWppIconFloatCenter } from './wpp-icon-float-center.js';
export { WppIconFloatLeft, defineCustomElement as defineCustomElementWppIconFloatLeft } from './wpp-icon-float-left.js';
export { WppIconFloatRight, defineCustomElement as defineCustomElementWppIconFloatRight } from './wpp-icon-float-right.js';
export { WppIconFluidWorkflow, defineCustomElement as defineCustomElementWppIconFluidWorkflow } from './wpp-icon-fluid-workflow.js';
export { WppIconFolder, defineCustomElement as defineCustomElementWppIconFolder } from './wpp-icon-folder.js';
export { WppIconFolderBlocked, defineCustomElement as defineCustomElementWppIconFolderBlocked } from './wpp-icon-folder-blocked.js';
export { WppIconFolderLink, defineCustomElement as defineCustomElementWppIconFolderLink } from './wpp-icon-folder-link.js';
export { WppIconFolderOpen, defineCustomElement as defineCustomElementWppIconFolderOpen } from './wpp-icon-folder-open.js';
export { WppIconFont, defineCustomElement as defineCustomElementWppIconFont } from './wpp-icon-font.js';
export { WppIconForward, defineCustomElement as defineCustomElementWppIconForward } from './wpp-icon-forward.js';
export { WppIconFullscreen, defineCustomElement as defineCustomElementWppIconFullscreen } from './wpp-icon-fullscreen.js';
export { WppIconFullscreenMinimise, defineCustomElement as defineCustomElementWppIconFullscreenMinimise } from './wpp-icon-fullscreen-minimise.js';
export { WppIconGallery, defineCustomElement as defineCustomElementWppIconGallery } from './wpp-icon-gallery.js';
export { WppIconGasStation, defineCustomElement as defineCustomElementWppIconGasStation } from './wpp-icon-gas-station.js';
export { WppIconGear, defineCustomElement as defineCustomElementWppIconGear } from './wpp-icon-gear.js';
export { WppIconGif, defineCustomElement as defineCustomElementWppIconGif } from './wpp-icon-gif.js';
export { WppIconGlobe, defineCustomElement as defineCustomElementWppIconGlobe } from './wpp-icon-globe.js';
export { WppIconGps, defineCustomElement as defineCustomElementWppIconGps } from './wpp-icon-gps.js';
export { WppIconGraph, defineCustomElement as defineCustomElementWppIconGraph } from './wpp-icon-graph.js';
export { WppIconGrid, defineCustomElement as defineCustomElementWppIconGrid } from './wpp-icon-grid.js';
export { WppIconH1, defineCustomElement as defineCustomElementWppIconH1 } from './wpp-icon-h1.js';
export { WppIconH2, defineCustomElement as defineCustomElementWppIconH2 } from './wpp-icon-h2.js';
export { WppIconH3, defineCustomElement as defineCustomElementWppIconH3 } from './wpp-icon-h3.js';
export { WppIconHandDraw, defineCustomElement as defineCustomElementWppIconHandDraw } from './wpp-icon-hand-draw.js';
export { WppIconHandOff, defineCustomElement as defineCustomElementWppIconHandOff } from './wpp-icon-hand-off.js';
export { WppIconHandOn, defineCustomElement as defineCustomElementWppIconHandOn } from './wpp-icon-hand-on.js';
export { WppIconHash, defineCustomElement as defineCustomElementWppIconHash } from './wpp-icon-hash.js';
export { WppIconHd, defineCustomElement as defineCustomElementWppIconHd } from './wpp-icon-hd.js';
export { WppIconHdr, defineCustomElement as defineCustomElementWppIconHdr } from './wpp-icon-hdr.js';
export { WppIconHeadphones, defineCustomElement as defineCustomElementWppIconHeadphones } from './wpp-icon-headphones.js';
export { WppIconHelp, defineCustomElement as defineCustomElementWppIconHelp } from './wpp-icon-help.js';
export { WppIconHistory, defineCustomElement as defineCustomElementWppIconHistory } from './wpp-icon-history.js';
export { WppIconHome, defineCustomElement as defineCustomElementWppIconHome } from './wpp-icon-home.js';
export { WppIconHomeCheckmark, defineCustomElement as defineCustomElementWppIconHomeCheckmark } from './wpp-icon-home-checkmark.js';
export { WppIconHospital, defineCustomElement as defineCustomElementWppIconHospital } from './wpp-icon-hospital.js';
export { WppIconHub, defineCustomElement as defineCustomElementWppIconHub } from './wpp-icon-hub.js';
export { WppIconIcons, defineCustomElement as defineCustomElementWppIconIcons } from './wpp-icon-icons.js';
export { WppIconIdea, defineCustomElement as defineCustomElementWppIconIdea } from './wpp-icon-idea.js';
export { WppIconIframe, defineCustomElement as defineCustomElementWppIconIframe } from './wpp-icon-iframe.js';
export { WppIconImage, defineCustomElement as defineCustomElementWppIconImage } from './wpp-icon-image.js';
export { WppIconImageOff, defineCustomElement as defineCustomElementWppIconImageOff } from './wpp-icon-image-off.js';
export { WppIconImport, defineCustomElement as defineCustomElementWppIconImport } from './wpp-icon-import.js';
export { WppIconInbox, defineCustomElement as defineCustomElementWppIconInbox } from './wpp-icon-inbox.js';
export { WppIconIncognito, defineCustomElement as defineCustomElementWppIconIncognito } from './wpp-icon-incognito.js';
export { WppIconIncomplete, defineCustomElement as defineCustomElementWppIconIncomplete } from './wpp-icon-incomplete.js';
export { WppIconIncrease, defineCustomElement as defineCustomElementWppIconIncrease } from './wpp-icon-increase.js';
export { WppIconIndentDecrease, defineCustomElement as defineCustomElementWppIconIndentDecrease } from './wpp-icon-indent-decrease.js';
export { WppIconIndentIncrease, defineCustomElement as defineCustomElementWppIconIndentIncrease } from './wpp-icon-indent-increase.js';
export { WppIconInfo, defineCustomElement as defineCustomElementWppIconInfo } from './wpp-icon-info.js';
export { WppIconInfoMessage, defineCustomElement as defineCustomElementWppIconInfoMessage } from './wpp-icon-info-message.js';
export { WppIconInstallUpdate, defineCustomElement as defineCustomElementWppIconInstallUpdate } from './wpp-icon-install-update.js';
export { WppIconItalic, defineCustomElement as defineCustomElementWppIconItalic } from './wpp-icon-italic.js';
export { WppIconJavaScript, defineCustomElement as defineCustomElementWppIconJavaScript } from './wpp-icon-java-script.js';
export { WppIconJoin, defineCustomElement as defineCustomElementWppIconJoin } from './wpp-icon-join.js';
export { WppIconKey, defineCustomElement as defineCustomElementWppIconKey } from './wpp-icon-key.js';
export { WppIconKeyboard, defineCustomElement as defineCustomElementWppIconKeyboard } from './wpp-icon-keyboard.js';
export { WppIconLaptop, defineCustomElement as defineCustomElementWppIconLaptop } from './wpp-icon-laptop.js';
export { WppIconLaugh, defineCustomElement as defineCustomElementWppIconLaugh } from './wpp-icon-laugh.js';
export { WppIconLaunch, defineCustomElement as defineCustomElementWppIconLaunch } from './wpp-icon-launch.js';
export { WppIconLayer, defineCustomElement as defineCustomElementWppIconLayer } from './wpp-icon-layer.js';
export { WppIconLeaf, defineCustomElement as defineCustomElementWppIconLeaf } from './wpp-icon-leaf.js';
export { WppIconLibrary, defineCustomElement as defineCustomElementWppIconLibrary } from './wpp-icon-library.js';
export { WppIconLibraryBuilding, defineCustomElement as defineCustomElementWppIconLibraryBuilding } from './wpp-icon-library-building.js';
export { WppIconLikeOff, defineCustomElement as defineCustomElementWppIconLikeOff } from './wpp-icon-like-off.js';
export { WppIconLikeOn, defineCustomElement as defineCustomElementWppIconLikeOn } from './wpp-icon-like-on.js';
export { WppIconLink, defineCustomElement as defineCustomElementWppIconLink } from './wpp-icon-link.js';
export { WppIconLive, defineCustomElement as defineCustomElementWppIconLive } from './wpp-icon-live.js';
export { WppIconLocation, defineCustomElement as defineCustomElementWppIconLocation } from './wpp-icon-location.js';
export { WppIconLockOff, defineCustomElement as defineCustomElementWppIconLockOff } from './wpp-icon-lock-off.js';
export { WppIconLockOn, defineCustomElement as defineCustomElementWppIconLockOn } from './wpp-icon-lock-on.js';
export { WppIconLodging, defineCustomElement as defineCustomElementWppIconLodging } from './wpp-icon-lodging.js';
export { WppIconLogin, defineCustomElement as defineCustomElementWppIconLogin } from './wpp-icon-login.js';
export { WppIconLogout, defineCustomElement as defineCustomElementWppIconLogout } from './wpp-icon-logout.js';
export { WppIconMagicWand, defineCustomElement as defineCustomElementWppIconMagicWand } from './wpp-icon-magic-wand.js';
export { WppIconMail, defineCustomElement as defineCustomElementWppIconMail } from './wpp-icon-mail.js';
export { WppIconMailAdd, defineCustomElement as defineCustomElementWppIconMailAdd } from './wpp-icon-mail-add.js';
export { WppIconMailAllRead, defineCustomElement as defineCustomElementWppIconMailAllRead } from './wpp-icon-mail-all-read.js';
export { WppIconMailBlocked, defineCustomElement as defineCustomElementWppIconMailBlocked } from './wpp-icon-mail-blocked.js';
export { WppIconMailCopy, defineCustomElement as defineCustomElementWppIconMailCopy } from './wpp-icon-mail-copy.js';
export { WppIconMailOff, defineCustomElement as defineCustomElementWppIconMailOff } from './wpp-icon-mail-off.js';
export { WppIconMailRead, defineCustomElement as defineCustomElementWppIconMailRead } from './wpp-icon-mail-read.js';
export { WppIconMap, defineCustomElement as defineCustomElementWppIconMap } from './wpp-icon-map.js';
export { WppIconMathFormula, defineCustomElement as defineCustomElementWppIconMathFormula } from './wpp-icon-math-formula.js';
export { WppIconMaximise, defineCustomElement as defineCustomElementWppIconMaximise } from './wpp-icon-maximise.js';
export { WppIconMeet, defineCustomElement as defineCustomElementWppIconMeet } from './wpp-icon-meet.js';
export { WppIconMention, defineCustomElement as defineCustomElementWppIconMention } from './wpp-icon-mention.js';
export { WppIconMerge, defineCustomElement as defineCustomElementWppIconMerge } from './wpp-icon-merge.js';
export { WppIconMicBlocked, defineCustomElement as defineCustomElementWppIconMicBlocked } from './wpp-icon-mic-blocked.js';
export { WppIconMicOff, defineCustomElement as defineCustomElementWppIconMicOff } from './wpp-icon-mic-off.js';
export { WppIconMicOn, defineCustomElement as defineCustomElementWppIconMicOn } from './wpp-icon-mic-on.js';
export { WppIconMinimise, defineCustomElement as defineCustomElementWppIconMinimise } from './wpp-icon-minimise.js';
export { WppIconMobile, defineCustomElement as defineCustomElementWppIconMobile } from './wpp-icon-mobile.js';
export { WppIconMoney, defineCustomElement as defineCustomElementWppIconMoney } from './wpp-icon-money.js';
export { WppIconMore, defineCustomElement as defineCustomElementWppIconMore } from './wpp-icon-more.js';
export { WppIconMove, defineCustomElement as defineCustomElementWppIconMove } from './wpp-icon-move.js';
export { WppIconMovie, defineCustomElement as defineCustomElementWppIconMovie } from './wpp-icon-movie.js';
export { WppIconMultipleEmotions, defineCustomElement as defineCustomElementWppIconMultipleEmotions } from './wpp-icon-multiple-emotions.js';
export { WppIconMusic, defineCustomElement as defineCustomElementWppIconMusic } from './wpp-icon-music.js';
export { WppIconNavigationMenu, defineCustomElement as defineCustomElementWppIconNavigationMenu } from './wpp-icon-navigation-menu.js';
export { WppIconNeutral, defineCustomElement as defineCustomElementWppIconNeutral } from './wpp-icon-neutral.js';
export { WppIconNeutralTrading, defineCustomElement as defineCustomElementWppIconNeutralTrading } from './wpp-icon-neutral-trading.js';
export { WppIconNewspaper, defineCustomElement as defineCustomElementWppIconNewspaper } from './wpp-icon-newspaper.js';
export { WppIconNext, defineCustomElement as defineCustomElementWppIconNext } from './wpp-icon-next.js';
export { WppIconNextFilled, defineCustomElement as defineCustomElementWppIconNextFilled } from './wpp-icon-next-filled.js';
export { WppIconNightLife, defineCustomElement as defineCustomElementWppIconNightLife } from './wpp-icon-night-life.js';
export { WppIconNote, defineCustomElement as defineCustomElementWppIconNote } from './wpp-icon-note.js';
export { WppIconNotificationNew, defineCustomElement as defineCustomElementWppIconNotificationNew } from './wpp-icon-notification-new.js';
export { WppIconNotificationPause, defineCustomElement as defineCustomElementWppIconNotificationPause } from './wpp-icon-notification-pause.js';
export { WppIconNuclearDanger, defineCustomElement as defineCustomElementWppIconNuclearDanger } from './wpp-icon-nuclear-danger.js';
export { WppIconNumber, defineCustomElement as defineCustomElementWppIconNumber } from './wpp-icon-number.js';
export { WppIconObjectAlignment, defineCustomElement as defineCustomElementWppIconObjectAlignment } from './wpp-icon-object-alignment.js';
export { WppIconObjectAlignmentCenter, defineCustomElement as defineCustomElementWppIconObjectAlignmentCenter } from './wpp-icon-object-alignment-center.js';
export { WppIconOrderedList, defineCustomElement as defineCustomElementWppIconOrderedList } from './wpp-icon-ordered-list.js';
export { WppIconOrganization, defineCustomElement as defineCustomElementWppIconOrganization } from './wpp-icon-organization.js';
export { WppIconOrientation, defineCustomElement as defineCustomElementWppIconOrientation } from './wpp-icon-orientation.js';
export { WppIconOutdoor, defineCustomElement as defineCustomElementWppIconOutdoor } from './wpp-icon-outdoor.js';
export { WppIconOutdoorMedia, defineCustomElement as defineCustomElementWppIconOutdoorMedia } from './wpp-icon-outdoor-media.js';
export { WppIconOwner, defineCustomElement as defineCustomElementWppIconOwner } from './wpp-icon-owner.js';
export { WppIconPadding, defineCustomElement as defineCustomElementWppIconPadding } from './wpp-icon-padding.js';
export { WppIconPair, defineCustomElement as defineCustomElementWppIconPair } from './wpp-icon-pair.js';
export { WppIconParking, defineCustomElement as defineCustomElementWppIconParking } from './wpp-icon-parking.js';
export { WppIconPaste, defineCustomElement as defineCustomElementWppIconPaste } from './wpp-icon-paste.js';
export { WppIconPause, defineCustomElement as defineCustomElementWppIconPause } from './wpp-icon-pause.js';
export { WppIconPauseFilled, defineCustomElement as defineCustomElementWppIconPauseFilled } from './wpp-icon-pause-filled.js';
export { WppIconPen, defineCustomElement as defineCustomElementWppIconPen } from './wpp-icon-pen.js';
export { WppIconPending, defineCustomElement as defineCustomElementWppIconPending } from './wpp-icon-pending.js';
export { WppIconPentagon, defineCustomElement as defineCustomElementWppIconPentagon } from './wpp-icon-pentagon.js';
export { WppIconPeople, defineCustomElement as defineCustomElementWppIconPeople } from './wpp-icon-people.js';
export { WppIconPharmacy, defineCustomElement as defineCustomElementWppIconPharmacy } from './wpp-icon-pharmacy.js';
export { WppIconPhone, defineCustomElement as defineCustomElementWppIconPhone } from './wpp-icon-phone.js';
export { WppIconPieChart, defineCustomElement as defineCustomElementWppIconPieChart } from './wpp-icon-pie-chart.js';
export { WppIconPinned, defineCustomElement as defineCustomElementWppIconPinned } from './wpp-icon-pinned.js';
export { WppIconPitch, defineCustomElement as defineCustomElementWppIconPitch } from './wpp-icon-pitch.js';
export { WppIconPlay, defineCustomElement as defineCustomElementWppIconPlay } from './wpp-icon-play.js';
export { WppIconPlayFilled, defineCustomElement as defineCustomElementWppIconPlayFilled } from './wpp-icon-play-filled.js';
export { WppIconPlus, defineCustomElement as defineCustomElementWppIconPlus } from './wpp-icon-plus.js';
export { WppIconPlusCircle, defineCustomElement as defineCustomElementWppIconPlusCircle } from './wpp-icon-plus-circle.js';
export { WppIconPolice, defineCustomElement as defineCustomElementWppIconPolice } from './wpp-icon-police.js';
export { WppIconPost, defineCustomElement as defineCustomElementWppIconPost } from './wpp-icon-post.js';
export { WppIconPound, defineCustomElement as defineCustomElementWppIconPound } from './wpp-icon-pound.js';
export { WppIconPremium, defineCustomElement as defineCustomElementWppIconPremium } from './wpp-icon-premium.js';
export { WppIconPrevious, defineCustomElement as defineCustomElementWppIconPrevious } from './wpp-icon-previous.js';
export { WppIconPreviousFilled, defineCustomElement as defineCustomElementWppIconPreviousFilled } from './wpp-icon-previous-filled.js';
export { WppIconPrint, defineCustomElement as defineCustomElementWppIconPrint } from './wpp-icon-print.js';
export { WppIconPrivateAccount, defineCustomElement as defineCustomElementWppIconPrivateAccount } from './wpp-icon-private-account.js';
export { WppIconQa, defineCustomElement as defineCustomElementWppIconQa } from './wpp-icon-qa.js';
export { WppIconQrCode, defineCustomElement as defineCustomElementWppIconQrCode } from './wpp-icon-qr-code.js';
export { WppIconRadio, defineCustomElement as defineCustomElementWppIconRadio } from './wpp-icon-radio.js';
export { WppIconRanking, defineCustomElement as defineCustomElementWppIconRanking } from './wpp-icon-ranking.js';
export { WppIconRatio, defineCustomElement as defineCustomElementWppIconRatio } from './wpp-icon-ratio.js';
export { WppIconRecord, defineCustomElement as defineCustomElementWppIconRecord } from './wpp-icon-record.js';
export { WppIconRecordStop, defineCustomElement as defineCustomElementWppIconRecordStop } from './wpp-icon-record-stop.js';
export { WppIconRectangle, defineCustomElement as defineCustomElementWppIconRectangle } from './wpp-icon-rectangle.js';
export { WppIconRecycle, defineCustomElement as defineCustomElementWppIconRecycle } from './wpp-icon-recycle.js';
export { WppIconRedo, defineCustomElement as defineCustomElementWppIconRedo } from './wpp-icon-redo.js';
export { WppIconRefresh, defineCustomElement as defineCustomElementWppIconRefresh } from './wpp-icon-refresh.js';
export { WppIconRefreshDashed, defineCustomElement as defineCustomElementWppIconRefreshDashed } from './wpp-icon-refresh-dashed.js';
export { WppIconReject, defineCustomElement as defineCustomElementWppIconReject } from './wpp-icon-reject.js';
export { WppIconRemove, defineCustomElement as defineCustomElementWppIconRemove } from './wpp-icon-remove.js';
export { WppIconRemoveApp, defineCustomElement as defineCustomElementWppIconRemoveApp } from './wpp-icon-remove-app.js';
export { WppIconRemoveCircle, defineCustomElement as defineCustomElementWppIconRemoveCircle } from './wpp-icon-remove-circle.js';
export { WppIconRepeatOff, defineCustomElement as defineCustomElementWppIconRepeatOff } from './wpp-icon-repeat-off.js';
export { WppIconRepeatOn, defineCustomElement as defineCustomElementWppIconRepeatOn } from './wpp-icon-repeat-on.js';
export { WppIconReply, defineCustomElement as defineCustomElementWppIconReply } from './wpp-icon-reply.js';
export { WppIconReplyAll, defineCustomElement as defineCustomElementWppIconReplyAll } from './wpp-icon-reply-all.js';
export { WppIconReset, defineCustomElement as defineCustomElementWppIconReset } from './wpp-icon-reset.js';
export { WppIconResetDashed, defineCustomElement as defineCustomElementWppIconResetDashed } from './wpp-icon-reset-dashed.js';
export { WppIconResize, defineCustomElement as defineCustomElementWppIconResize } from './wpp-icon-resize.js';
export { WppIconResizeLarge, defineCustomElement as defineCustomElementWppIconResizeLarge } from './wpp-icon-resize-large.js';
export { WppIconResizeSmall, defineCustomElement as defineCustomElementWppIconResizeSmall } from './wpp-icon-resize-small.js';
export { WppIconRestaurant, defineCustomElement as defineCustomElementWppIconRestaurant } from './wpp-icon-restaurant.js';
export { WppIconRhombus, defineCustomElement as defineCustomElementWppIconRhombus } from './wpp-icon-rhombus.js';
export { WppIconRotate, defineCustomElement as defineCustomElementWppIconRotate } from './wpp-icon-rotate.js';
export { WppIconRotateClockwise, defineCustomElement as defineCustomElementWppIconRotateClockwise } from './wpp-icon-rotate-clockwise.js';
export { WppIconRotateCounterclockwise, defineCustomElement as defineCustomElementWppIconRotateCounterclockwise } from './wpp-icon-rotate-counterclockwise.js';
export { WppIconRss, defineCustomElement as defineCustomElementWppIconRss } from './wpp-icon-rss.js';
export { WppIconRupee, defineCustomElement as defineCustomElementWppIconRupee } from './wpp-icon-rupee.js';
export { WppIconSad, defineCustomElement as defineCustomElementWppIconSad } from './wpp-icon-sad.js';
export { WppIconSadSlightly, defineCustomElement as defineCustomElementWppIconSadSlightly } from './wpp-icon-sad-slightly.js';
export { WppIconScale, defineCustomElement as defineCustomElementWppIconScale } from './wpp-icon-scale.js';
export { WppIconScaleBottom, defineCustomElement as defineCustomElementWppIconScaleBottom } from './wpp-icon-scale-bottom.js';
export { WppIconScan, defineCustomElement as defineCustomElementWppIconScan } from './wpp-icon-scan.js';
export { WppIconSchool, defineCustomElement as defineCustomElementWppIconSchool } from './wpp-icon-school.js';
export { WppIconSearch, defineCustomElement as defineCustomElementWppIconSearch } from './wpp-icon-search.js';
export { WppIconSegmentedControl, defineCustomElement as defineCustomElementWppIconSegmentedControl } from './wpp-icon-segmented-control.js';
export { WppIconSelectObject, defineCustomElement as defineCustomElementWppIconSelectObject } from './wpp-icon-select-object.js';
export { WppIconSend, defineCustomElement as defineCustomElementWppIconSend } from './wpp-icon-send.js';
export { WppIconSendOff, defineCustomElement as defineCustomElementWppIconSendOff } from './wpp-icon-send-off.js';
export { WppIconService, defineCustomElement as defineCustomElementWppIconService } from './wpp-icon-service.js';
export { WppIconShapes, defineCustomElement as defineCustomElementWppIconShapes } from './wpp-icon-shapes.js';
export { WppIconShare, defineCustomElement as defineCustomElementWppIconShare } from './wpp-icon-share.js';
export { WppIconShield, defineCustomElement as defineCustomElementWppIconShield } from './wpp-icon-shield.js';
export { WppIconShieldDismiss, defineCustomElement as defineCustomElementWppIconShieldDismiss } from './wpp-icon-shield-dismiss.js';
export { WppIconShieldError, defineCustomElement as defineCustomElementWppIconShieldError } from './wpp-icon-shield-error.js';
export { WppIconShieldSuccess, defineCustomElement as defineCustomElementWppIconShieldSuccess } from './wpp-icon-shield-success.js';
export { WppIconShip, defineCustomElement as defineCustomElementWppIconShip } from './wpp-icon-ship.js';
export { WppIconShopping, defineCustomElement as defineCustomElementWppIconShopping } from './wpp-icon-shopping.js';
export { WppIconShutDown, defineCustomElement as defineCustomElementWppIconShutDown } from './wpp-icon-shut-down.js';
export { WppIconSmartwatch, defineCustomElement as defineCustomElementWppIconSmartwatch } from './wpp-icon-smartwatch.js';
export { WppIconSmile, defineCustomElement as defineCustomElementWppIconSmile } from './wpp-icon-smile.js';
export { WppIconSmileSlightly, defineCustomElement as defineCustomElementWppIconSmileSlightly } from './wpp-icon-smile-slightly.js';
export { WppIconSocialMedia, defineCustomElement as defineCustomElementWppIconSocialMedia } from './wpp-icon-social-media.js';
export { WppIconSort, defineCustomElement as defineCustomElementWppIconSort } from './wpp-icon-sort.js';
export { WppIconSortDecrease, defineCustomElement as defineCustomElementWppIconSortDecrease } from './wpp-icon-sort-decrease.js';
export { WppIconSortIncrease, defineCustomElement as defineCustomElementWppIconSortIncrease } from './wpp-icon-sort-increase.js';
export { WppIconSparkle, defineCustomElement as defineCustomElementWppIconSparkle } from './wpp-icon-sparkle.js';
export { WppIconSpeaker, defineCustomElement as defineCustomElementWppIconSpeaker } from './wpp-icon-speaker.js';
export { WppIconSpeakerBluetooth, defineCustomElement as defineCustomElementWppIconSpeakerBluetooth } from './wpp-icon-speaker-bluetooth.js';
export { WppIconSpeakerMute, defineCustomElement as defineCustomElementWppIconSpeakerMute } from './wpp-icon-speaker-mute.js';
export { WppIconSpeakerOff, defineCustomElement as defineCustomElementWppIconSpeakerOff } from './wpp-icon-speaker-off.js';
export { WppIconSplit, defineCustomElement as defineCustomElementWppIconSplit } from './wpp-icon-split.js';
export { WppIconSport, defineCustomElement as defineCustomElementWppIconSport } from './wpp-icon-sport.js';
export { WppIconSpreadsheet, defineCustomElement as defineCustomElementWppIconSpreadsheet } from './wpp-icon-spreadsheet.js';
export { WppIconSquare, defineCustomElement as defineCustomElementWppIconSquare } from './wpp-icon-square.js';
export { WppIconSquareHint, defineCustomElement as defineCustomElementWppIconSquareHint } from './wpp-icon-square-hint.js';
export { WppIconStatisticDocument, defineCustomElement as defineCustomElementWppIconStatisticDocument } from './wpp-icon-statistic-document.js';
export { WppIconSticker, defineCustomElement as defineCustomElementWppIconSticker } from './wpp-icon-sticker.js';
export { WppIconStop, defineCustomElement as defineCustomElementWppIconStop } from './wpp-icon-stop.js';
export { WppIconStopFilled, defineCustomElement as defineCustomElementWppIconStopFilled } from './wpp-icon-stop-filled.js';
export { WppIconStrikeThrough, defineCustomElement as defineCustomElementWppIconStrikeThrough } from './wpp-icon-strike-through.js';
export { WppIconStyleguide, defineCustomElement as defineCustomElementWppIconStyleguide } from './wpp-icon-styleguide.js';
export { WppIconSubItems, defineCustomElement as defineCustomElementWppIconSubItems } from './wpp-icon-sub-items.js';
export { WppIconSubscribe, defineCustomElement as defineCustomElementWppIconSubscribe } from './wpp-icon-subscribe.js';
export { WppIconSuccess, defineCustomElement as defineCustomElementWppIconSuccess } from './wpp-icon-success.js';
export { WppIconSupermarket, defineCustomElement as defineCustomElementWppIconSupermarket } from './wpp-icon-supermarket.js';
export { WppIconSupport, defineCustomElement as defineCustomElementWppIconSupport } from './wpp-icon-support.js';
export { WppIconSupportChat, defineCustomElement as defineCustomElementWppIconSupportChat } from './wpp-icon-support-chat.js';
export { WppIconSurprise, defineCustomElement as defineCustomElementWppIconSurprise } from './wpp-icon-surprise.js';
export { WppIconSwatch, defineCustomElement as defineCustomElementWppIconSwatch } from './wpp-icon-swatch.js';
export { WppIconSymbols, defineCustomElement as defineCustomElementWppIconSymbols } from './wpp-icon-symbols.js';
export { WppIconSync, defineCustomElement as defineCustomElementWppIconSync } from './wpp-icon-sync.js';
export { WppIconTableDefault, defineCustomElement as defineCustomElementWppIconTableDefault } from './wpp-icon-table-default.js';
export { WppIconTableDismiss, defineCustomElement as defineCustomElementWppIconTableDismiss } from './wpp-icon-table-dismiss.js';
export { WppIconTableEdit, defineCustomElement as defineCustomElementWppIconTableEdit } from './wpp-icon-table-edit.js';
export { WppIconTableLink, defineCustomElement as defineCustomElementWppIconTableLink } from './wpp-icon-table-link.js';
export { WppIconTableSimple, defineCustomElement as defineCustomElementWppIconTableSimple } from './wpp-icon-table-simple.js';
export { WppIconTableSort, defineCustomElement as defineCustomElementWppIconTableSort } from './wpp-icon-table-sort.js';
export { WppIconTableSortAsc, defineCustomElement as defineCustomElementWppIconTableSortAsc } from './wpp-icon-table-sort-asc.js';
export { WppIconTableSortAscHover, defineCustomElement as defineCustomElementWppIconTableSortAscHover } from './wpp-icon-table-sort-asc-hover.js';
export { WppIconTableSortAscPressed, defineCustomElement as defineCustomElementWppIconTableSortAscPressed } from './wpp-icon-table-sort-asc-pressed.js';
export { WppIconTableSortDesc, defineCustomElement as defineCustomElementWppIconTableSortDesc } from './wpp-icon-table-sort-desc.js';
export { WppIconTableSortDescHover, defineCustomElement as defineCustomElementWppIconTableSortDescHover } from './wpp-icon-table-sort-desc-hover.js';
export { WppIconTableSortDescPressed, defineCustomElement as defineCustomElementWppIconTableSortDescPressed } from './wpp-icon-table-sort-desc-pressed.js';
export { WppIconTableSortHover, defineCustomElement as defineCustomElementWppIconTableSortHover } from './wpp-icon-table-sort-hover.js';
export { WppIconTableSortPressed, defineCustomElement as defineCustomElementWppIconTableSortPressed } from './wpp-icon-table-sort-pressed.js';
export { WppIconTableSortWrapper, defineCustomElement as defineCustomElementWppIconTableSortWrapper } from './wpp-icon-table-sort-wrapper.js';
export { WppIconTablet, defineCustomElement as defineCustomElementWppIconTablet } from './wpp-icon-tablet.js';
export { WppIconTag, defineCustomElement as defineCustomElementWppIconTag } from './wpp-icon-tag.js';
export { WppIconTarget, defineCustomElement as defineCustomElementWppIconTarget } from './wpp-icon-target.js';
export { WppIconTaskList, defineCustomElement as defineCustomElementWppIconTaskList } from './wpp-icon-task-list.js';
export { WppIconTaskListSquare, defineCustomElement as defineCustomElementWppIconTaskListSquare } from './wpp-icon-task-list-square.js';
export { WppIconText, defineCustomElement as defineCustomElementWppIconText } from './wpp-icon-text.js';
export { WppIconTextAlignmentCenter, defineCustomElement as defineCustomElementWppIconTextAlignmentCenter } from './wpp-icon-text-alignment-center.js';
export { WppIconTextAlignmentDistribute, defineCustomElement as defineCustomElementWppIconTextAlignmentDistribute } from './wpp-icon-text-alignment-distribute.js';
export { WppIconTextAlignmentDistributeVertical, defineCustomElement as defineCustomElementWppIconTextAlignmentDistributeVertical } from './wpp-icon-text-alignment-distribute-vertical.js';
export { WppIconTextAlignmentJustify, defineCustomElement as defineCustomElementWppIconTextAlignmentJustify } from './wpp-icon-text-alignment-justify.js';
export { WppIconTextAlignmentJustifyLow, defineCustomElement as defineCustomElementWppIconTextAlignmentJustifyLow } from './wpp-icon-text-alignment-justify-low.js';
export { WppIconTextAlignmentLeft, defineCustomElement as defineCustomElementWppIconTextAlignmentLeft } from './wpp-icon-text-alignment-left.js';
export { WppIconTextAlignmentRight, defineCustomElement as defineCustomElementWppIconTextAlignmentRight } from './wpp-icon-text-alignment-right.js';
export { WppIconTheatre, defineCustomElement as defineCustomElementWppIconTheatre } from './wpp-icon-theatre.js';
export { WppIconThumbsDown, defineCustomElement as defineCustomElementWppIconThumbsDown } from './wpp-icon-thumbs-down.js';
export { WppIconThumbsDownFilled, defineCustomElement as defineCustomElementWppIconThumbsDownFilled } from './wpp-icon-thumbs-down-filled.js';
export { WppIconThumbsUp, defineCustomElement as defineCustomElementWppIconThumbsUp } from './wpp-icon-thumbs-up.js';
export { WppIconThumbsUpFilled, defineCustomElement as defineCustomElementWppIconThumbsUpFilled } from './wpp-icon-thumbs-up-filled.js';
export { WppIconTick, defineCustomElement as defineCustomElementWppIconTick } from './wpp-icon-tick.js';
export { WppIconTourism, defineCustomElement as defineCustomElementWppIconTourism } from './wpp-icon-tourism.js';
export { WppIconTrain, defineCustomElement as defineCustomElementWppIconTrain } from './wpp-icon-train.js';
export { WppIconTranslate, defineCustomElement as defineCustomElementWppIconTranslate } from './wpp-icon-translate.js';
export { WppIconTransparent, defineCustomElement as defineCustomElementWppIconTransparent } from './wpp-icon-transparent.js';
export { WppIconTrash, defineCustomElement as defineCustomElementWppIconTrash } from './wpp-icon-trash.js';
export { WppIconTrendAscend, defineCustomElement as defineCustomElementWppIconTrendAscend } from './wpp-icon-trend-ascend.js';
export { WppIconTrendDescent, defineCustomElement as defineCustomElementWppIconTrendDescent } from './wpp-icon-trend-descent.js';
export { WppIconTriangle, defineCustomElement as defineCustomElementWppIconTriangle } from './wpp-icon-triangle.js';
export { WppIconTriangleFill, defineCustomElement as defineCustomElementWppIconTriangleFill } from './wpp-icon-triangle-fill.js';
export { WppIconTune, defineCustomElement as defineCustomElementWppIconTune } from './wpp-icon-tune.js';
export { WppIconTv, defineCustomElement as defineCustomElementWppIconTv } from './wpp-icon-tv.js';
export { WppIconTwentyFourHours, defineCustomElement as defineCustomElementWppIconTwentyFourHours } from './wpp-icon-twenty-four-hours.js';
export { WppIconUnderline, defineCustomElement as defineCustomElementWppIconUnderline } from './wpp-icon-underline.js';
export { WppIconUndo, defineCustomElement as defineCustomElementWppIconUndo } from './wpp-icon-undo.js';
export { WppIconUnlink, defineCustomElement as defineCustomElementWppIconUnlink } from './wpp-icon-unlink.js';
export { WppIconUnorderedList, defineCustomElement as defineCustomElementWppIconUnorderedList } from './wpp-icon-unordered-list.js';
export { WppIconUnpinned, defineCustomElement as defineCustomElementWppIconUnpinned } from './wpp-icon-unpinned.js';
export { WppIconUpload, defineCustomElement as defineCustomElementWppIconUpload } from './wpp-icon-upload.js';
export { WppIconUser, defineCustomElement as defineCustomElementWppIconUser } from './wpp-icon-user.js';
export { WppIconUserAdd, defineCustomElement as defineCustomElementWppIconUserAdd } from './wpp-icon-user-add.js';
export { WppIconUserBlock, defineCustomElement as defineCustomElementWppIconUserBlock } from './wpp-icon-user-block.js';
export { WppIconUserChat, defineCustomElement as defineCustomElementWppIconUserChat } from './wpp-icon-user-chat.js';
export { WppIconUserSearch, defineCustomElement as defineCustomElementWppIconUserSearch } from './wpp-icon-user-search.js';
export { WppIconUserStarred, defineCustomElement as defineCustomElementWppIconUserStarred } from './wpp-icon-user-starred.js';
export { WppIconUserTag, defineCustomElement as defineCustomElementWppIconUserTag } from './wpp-icon-user-tag.js';
export { WppIconVideoBlocked, defineCustomElement as defineCustomElementWppIconVideoBlocked } from './wpp-icon-video-blocked.js';
export { WppIconVideoClip, defineCustomElement as defineCustomElementWppIconVideoClip } from './wpp-icon-video-clip.js';
export { WppIconVideoOff, defineCustomElement as defineCustomElementWppIconVideoOff } from './wpp-icon-video-off.js';
export { WppIconVideoOn, defineCustomElement as defineCustomElementWppIconVideoOn } from './wpp-icon-video-on.js';
export { WppIconVr, defineCustomElement as defineCustomElementWppIconVr } from './wpp-icon-vr.js';
export { WppIconWarning, defineCustomElement as defineCustomElementWppIconWarning } from './wpp-icon-warning.js';
export { WppIconWifiOff, defineCustomElement as defineCustomElementWppIconWifiOff } from './wpp-icon-wifi-off.js';
export { WppIconWifiOn, defineCustomElement as defineCustomElementWppIconWifiOn } from './wpp-icon-wifi-on.js';
export { WppIconWifiWarning, defineCustomElement as defineCustomElementWppIconWifiWarning } from './wpp-icon-wifi-warning.js';
export { WppIconWithHand, defineCustomElement as defineCustomElementWppIconWithHand } from './wpp-icon-with-hand.js';
export { WppIconWorkshop, defineCustomElement as defineCustomElementWppIconWorkshop } from './wpp-icon-workshop.js';
export { WppIconWrapOff, defineCustomElement as defineCustomElementWppIconWrapOff } from './wpp-icon-wrap-off.js';
export { WppIconWrapOn, defineCustomElement as defineCustomElementWppIconWrapOn } from './wpp-icon-wrap-on.js';
export { WppIconYen, defineCustomElement as defineCustomElementWppIconYen } from './wpp-icon-yen.js';
export { WppIconYuan, defineCustomElement as defineCustomElementWppIconYuan } from './wpp-icon-yuan.js';
export { WppIconZoo, defineCustomElement as defineCustomElementWppIconZoo } from './wpp-icon-zoo.js';
export { WppIconZoomIn, defineCustomElement as defineCustomElementWppIconZoomIn } from './wpp-icon-zoom-in.js';
export { WppIconZoomOut, defineCustomElement as defineCustomElementWppIconZoomOut } from './wpp-icon-zoom-out.js';
export { WppInlineMessage, defineCustomElement as defineCustomElementWppInlineMessage } from './wpp-inline-message.js';
export { WppInput, defineCustomElement as defineCustomElementWppInput } from './wpp-input.js';
export { WppInternalLabel, defineCustomElement as defineCustomElementWppInternalLabel } from './wpp-internal-label.js';
export { WppInternalTooltip, defineCustomElement as defineCustomElementWppInternalTooltip } from './wpp-internal-tooltip.js';
export { WppLabel, defineCustomElement as defineCustomElementWppLabel } from './wpp-label.js';
export { WppLegend, defineCustomElement as defineCustomElementWppLegend } from './wpp-legend.js';
export { WppListItem, defineCustomElement as defineCustomElementWppListItem } from './wpp-list-item.js';
export { WppLoadMore, defineCustomElement as defineCustomElementWppLoadMore } from './wpp-load-more.js';
export { WppMenuContext, defineCustomElement as defineCustomElementWppMenuContext } from './wpp-menu-context.js';
export { WppMenuGroup, defineCustomElement as defineCustomElementWppMenuGroup } from './wpp-menu-group.js';
export { WppMoreButton, defineCustomElement as defineCustomElementWppMoreButton } from './wpp-more-button.js';
export { WppNavSidebar, defineCustomElement as defineCustomElementWppNavSidebar } from './wpp-nav-sidebar.js';
export { WppNavSidebarItem, defineCustomElement as defineCustomElementWppNavSidebarItem } from './wpp-nav-sidebar-item.js';
export { WppNavigationItem, defineCustomElement as defineCustomElementWppNavigationItem } from './wpp-navigation-item.js';
export { WppOpacitySlider, defineCustomElement as defineCustomElementWppOpacitySlider } from './wpp-opacity-slider.js';
export { WppOverlay, defineCustomElement as defineCustomElementWppOverlay } from './wpp-overlay.js';
export { WppPagination, defineCustomElement as defineCustomElementWppPagination } from './wpp-pagination.js';
export { WppPaginationItem, defineCustomElement as defineCustomElementWppPaginationItem } from './wpp-pagination-item.js';
export { WppPaginationSelect, defineCustomElement as defineCustomElementWppPaginationSelect } from './wpp-pagination-select.js';
export { WppPill, defineCustomElement as defineCustomElementWppPill } from './wpp-pill.js';
export { WppPillGroup, defineCustomElement as defineCustomElementWppPillGroup } from './wpp-pill-group.js';
export { WppPopover, defineCustomElement as defineCustomElementWppPopover } from './wpp-popover.js';
export { WppProgressIndicator, defineCustomElement as defineCustomElementWppProgressIndicator } from './wpp-progress-indicator.js';
export { WppQuillStyles, defineCustomElement as defineCustomElementWppQuillStyles } from './wpp-quill-styles.js';
export { WppRadio, defineCustomElement as defineCustomElementWppRadio } from './wpp-radio.js';
export { WppRadioGroup, defineCustomElement as defineCustomElementWppRadioGroup } from './wpp-radio-group.js';
export { WppRichtextCommonStyles, defineCustomElement as defineCustomElementWppRichtextCommonStyles } from './wpp-richtext-common-styles.js';
export { WppRichtextHtml, defineCustomElement as defineCustomElementWppRichtextHtml } from './wpp-richtext-html.js';
export { WppRichtextIconLoader, defineCustomElement as defineCustomElementWppRichtextIconLoader } from './wpp-richtext-icon-loader.js';
export { WppRichtextMarkdown, defineCustomElement as defineCustomElementWppRichtextMarkdown } from './wpp-richtext-markdown.js';
export { WppRichtextView, defineCustomElement as defineCustomElementWppRichtextView } from './wpp-richtext-view.js';
export { WppSaturationPicker, defineCustomElement as defineCustomElementWppSaturationPicker } from './wpp-saturation-picker.js';
export { WppSearch, defineCustomElement as defineCustomElementWppSearch } from './wpp-search.js';
export { WppSegmentedControl, defineCustomElement as defineCustomElementWppSegmentedControl } from './wpp-segmented-control.js';
export { WppSegmentedControlItem, defineCustomElement as defineCustomElementWppSegmentedControlItem } from './wpp-segmented-control-item.js';
export { WppSelect, defineCustomElement as defineCustomElementWppSelect } from './wpp-select.js';
export { WppSkeleton, defineCustomElement as defineCustomElementWppSkeleton } from './wpp-skeleton.js';
export { WppSlider, defineCustomElement as defineCustomElementWppSlider } from './wpp-slider.js';
export { WppSortButton, defineCustomElement as defineCustomElementWppSortButton } from './wpp-sort-button.js';
export { WppSpinner, defineCustomElement as defineCustomElementWppSpinner } from './wpp-spinner.js';
export { WppStep, defineCustomElement as defineCustomElementWppStep } from './wpp-step.js';
export { WppStepper, defineCustomElement as defineCustomElementWppStepper } from './wpp-stepper.js';
export { WppStickyBar, defineCustomElement as defineCustomElementWppStickyBar } from './wpp-sticky-bar.js';
export { WppTab, defineCustomElement as defineCustomElementWppTab } from './wpp-tab.js';
export { WppTabs, defineCustomElement as defineCustomElementWppTabs } from './wpp-tabs.js';
export { WppTag, defineCustomElement as defineCustomElementWppTag } from './wpp-tag.js';
export { WppTextareaInput, defineCustomElement as defineCustomElementWppTextareaInput } from './wpp-textarea-input.js';
export { WppTimePicker, defineCustomElement as defineCustomElementWppTimePicker } from './wpp-time-picker.js';
export { WppToast, defineCustomElement as defineCustomElementWppToast } from './wpp-toast.js';
export { WppToastContainer, defineCustomElement as defineCustomElementWppToastContainer } from './wpp-toast-container.js';
export { WppToggle, defineCustomElement as defineCustomElementWppToggle } from './wpp-toggle.js';
export { WppTooltip, defineCustomElement as defineCustomElementWppTooltip } from './wpp-tooltip.js';
export { WppTopbar, defineCustomElement as defineCustomElementWppTopbar } from './wpp-topbar.js';
export { WppTopbarItem, defineCustomElement as defineCustomElementWppTopbarItem } from './wpp-topbar-item.js';
export { WppTree, defineCustomElement as defineCustomElementWppTree } from './wpp-tree.js';
export { WppTreeItem, defineCustomElement as defineCustomElementWppTreeItem } from './wpp-tree-item.js';
export { WppTypography, defineCustomElement as defineCustomElementWppTypography } from './wpp-typography.js';
export { WppVideoPlayer, defineCustomElement as defineCustomElementWppVideoPlayer } from './wpp-video-player.js';

const dsPrefix = '--wpp';
/**
 * Function to transform incorrect color variable names to correct: '--wpp-color-primary-500' -> '--wpp-primary-color-500'
 */
const transformColorVariableNames = (theme) => Object.entries(theme).reduce((acc, [key, value]) => {
  if (key.includes('color') && key.indexOf('color') === 6) {
    const splittedKeys = key.slice(2).split('-');
    const temp = splittedKeys[1];
    splittedKeys[1] = splittedKeys[2];
    splittedKeys[2] = temp;
    const transformedKey = `--${splittedKeys.join('-')}`;
    return {
      ...acc,
      [transformedKey]: value,
    };
  }
  acc[key] = value;
  return {
    ...acc,
    [key]: value,
  };
}, {});
/**
 * Function to transform Theme properties from 'color.primary.500' to '#FFF',
 */
const transformJsonValueToCss = (theme, json) => {
  const updatedCssTokens = {};
  // TODO: improve typings
  // eslint-disable-next-line array-callback-return
  Object.entries(theme).reduce((acc, [key, value]) => {
    if (value?.startsWith('color.')) {
      const parsedValue = value.split('.').reduce((acc, currentProp) => acc[currentProp], json);
      updatedCssTokens[key] = parsedValue;
    }
  });
  return { ...theme, ...updatedCssTokens };
};
/**
 * Recursive function to iterate through theme properties and convert them to '--wpp-css-variable'
 */
const loopProperty = (obj, key, res) => Object.entries(obj).reduce((acc, [prop, value]) => {
  // if we face property with 'default' name - we should not add it to the css variable. E.g.  'color.brand.default' -> 'color-brand'
  const firstPart = key !== 'components' ? key : '';
  const secondPart = prop !== 'default' ? prop : '';
  const delimiter = firstPart && secondPart ? '-' : '';
  const newKey = toKebabCase(firstPart + delimiter + secondPart);
  if (secondPart === 'fontFamily' || (firstPart === 'font' && secondPart === 'family')) {
    return {
      ...acc,
      [`${dsPrefix}-${newKey}`]: Array.isArray(value) ? value.filter(i => i).join(', ') : value,
    };
  }
  else if (!isObject(value)) {
    return {
      ...acc,
      [`${dsPrefix}-${newKey}`]: value,
    };
  }
  else {
    return loopProperty(value, newKey, acc);
  }
}, res);
/**
 * Creates flat theme object from theme object
 */
const createTheme = (json, variant = 'light') => {
  const flatTheme = Object.entries(json.content[variant]).reduce((acc, [category, value]) => {
    if (isObject(value)) {
      return {
        ...acc,
        ...loopProperty(value, category, acc),
      };
    }
    return { ...acc, [toKebabCase(category)]: value };
  }, {});
  return transformJsonValueToCss(transformColorVariableNames(flatTheme), json.content[variant]);
};
/**
 * Resolve theme object with color values
 */
const resolveTheme = (initJson, variant = 'light') => {
  const json = { ...initJson };
  return recursiveObjectMap(json, value => {
    if (typeof value === 'string' && value.startsWith('color.')) {
      return value.split('.').reduce((acc, currentProp) => acc[currentProp], json.content[variant]);
    }
    return value;
  });
};

export { createTheme, resolveTheme };
