<script setup lang="ts">
import { ref } from "vue";

import {
  WppAccordion,
  WppAutocomplete,
  WppTypography,
  WppListItem,
} from "@platform-ui-kit/components-library-vue";

import ServerSearch from "./examples/ServerSearch.vue";
import InfiniteScrollWithLazyLoad from "./examples/InfiniteScrollWithLazyLoad.vue";
import ServerLoadSameOptionForDifferentSearch from "./examples/ServerLoadSameOptionForDifferentSearch.vue";
import WithoutSimpleSearch from "./examples/WithoutSimpleSearch.vue";
import SelectedValues from "./SelectedValues.vue";
import ResultsView from "./ResultsView.vue";

import type { BasicOption, CountryOption } from "./options";
import { fruitOptions, countryOptions, hugeListOptions } from "./options";

const basicValue = ref<BasicOption[]>([
  {
    id: 5,
    label: "Pineapple",
  },
  {
    id: 3,
    label: "Kiwi",
  },
  {
    id: 13,
    label: "Pear",
  },
]);

const customOptionsValue = ref<CountryOption[]>([]);
const hugeListValue = ref<BasicOption[]>([]);

const handleBasicValue = (event: CustomEvent) => {
  basicValue.value = event.detail.value;
};

const handleBasicValuePillCloseClick = (selectedValue: number) => {
  basicValue.value = basicValue.value.filter((i) => i.id !== selectedValue);
};

const handleCustomOptionsValue = (event: CustomEvent) => {
  customOptionsValue.value = event.detail.value;
};

const handleCustomValuePillCloseClick = (selectedValue: number) => {
  customOptionsValue.value = customOptionsValue.value.filter(
    (i) => i.id !== selectedValue
  );
};

const handleHugeListValue = (event: CustomEvent) => {
  hugeListValue.value = event.detail.value;
};

const handleHugeValuePillCloseClick = (selectedValue: number) => {
  hugeListValue.value = hugeListValue.value.filter(
    (i) => i.id !== selectedValue
  );
};
</script>

<template>
  <div>
    <div class="autocomplete-wrapper" data-testid="autocompletes">
      <div class="item">
        <WppAutocomplete
          required
          name="basic"
          :labelConfig="{
            icon: 'wpp-icon-info',
            text: 'Basic with initial values',
            description: 'Description',
            locales: {
              optional: 'Optional',
            },
          }"
          placeholder="Select fruits"
          @wppChange="handleBasicValue"
          data-testid="basic-autocomplete"
          multiple
          :value="basicValue"
          showCreateNewElement
          simpleSearch
        >
          <WppListItem
            v-for="option in fruitOptions"
            :key="option.id"
            :value="option"
            :label="option.label"
          >
            <p slot="label">{{ option.label }}</p>
          </WppListItem>
          <SelectedValues
            :values="basicValue"
            @closeClick="(value) => handleBasicValuePillCloseClick(value)"
          />
        </WppAutocomplete>
      </div>
      <div class="item">
        <WppAutocomplete
          required
          name="custom-option-labels"
          :labelConfig="{
            text: 'Custom option labels and modified number of tags shown when idle',
          }"
          placeholder="Select countries"
          :value="customOptionsValue"
          @wppChange="handleCustomOptionsValue"
          data-testid="custom-autocomplete"
          autoFocus
          multiple
          showCreateNewElement
          simpleSearch
        >
          <WppListItem
            v-for="option in countryOptions"
            :key="option.id"
            :value="option"
            :label="option.label"
          >
            <div slot="label">
              <div class="primary">
                <span class="flag">{{ option.flag }}</span> {{ option.label }}
              </div>
            </div>
            <div class="secondary" slot="caption">
              {{ option.nativeName }}
            </div>
          </WppListItem>
          <SelectedValues
            :values="customOptionsValue"
            @closeClick="(value) => handleCustomValuePillCloseClick(value)"
          />
        </WppAutocomplete>

        <ResultsView :value="customOptionsValue.map((i) => i.id)" />
      </div>

      <div class="item">
        <WppAutocomplete
          required
          name="huge-list"
          :labelConfig="{ text: 'Huge autogenerated list' }"
          placeholder="Select everything"
          :value="hugeListValue"
          @wppChange="handleHugeListValue"
          multiple
          showCreateNewElement
          simpleSearch
        >
          <WppListItem
            v-for="option in hugeListOptions"
            :key="option.id"
            :value="option"
            :label="option.label"
          >
            <p slot="label">{{ option.label }}</p>
          </WppListItem>

          <SelectedValues
            :values="hugeListValue"
            @closeClick="(value) => handleHugeValuePillCloseClick(value)"
          />
        </WppAutocomplete>

        <ResultsView :value="hugeListValue.length + ' option(s) selected'" />
      </div>

      <ServerSearch />
      <InfiniteScrollWithLazyLoad />
      <ServerLoadSameOptionForDifferentSearch />
      <WithoutSimpleSearch />

      <div class="item">
        <WppAccordion
          size="s"
          expanded
          counter="{3}"
          text="Autocomplete in Accordion"
        >
          <WppAutocomplete
            required
            name="basic"
            :labelConfig="{ text: 'Basic with initial values' }"
            placeholder="Select fruits"
            :value="basicValue"
            @wppChange="handleBasicValue"
            data-testid="basic-autocomplete"
            :dropdownConfig="{ popperOptions: { strategy: 'fixed' } }"
            multiple
            showCreateNewElement
            simpleSearch
          >
            <WppListItem
              v-for="option in fruitOptions"
              :key="option.id"
              :value="option"
              :label="option.label"
            >
              <p slot="label">{{ option.label }}</p>
            </WppListItem>
            <SelectedValues
              :values="basicValue"
              @closeClick="(value) => handleBasicValuePillCloseClick(value)"
            />
          </WppAutocomplete>
        </WppAccordion>
      </div>
    </div>

    <div class="empty">
      <WppTypography type="l-strong">
        Empty space to avoid scroll jumping
      </WppTypography>
    </div>
  </div>
</template>

<style>
.autocomplete-wrapper {
  box-sizing: border-box;
  width: 650px;
  margin: 24px auto;
  padding: 40px;
  border: 1px solid var(--wpp-grey-color-600);
  border-radius: 8px;
}

.item + .item {
  margin-top: 32px;
}

.primary {
  line-height: 18px;
}

.flag {
  font-size: 18px;
}

.secondary {
  color: var(--wpp-grey-color-600);
  font-size: 12px;
  line-height: 14px;
}

.empty {
  display: flex;
  align-items: center;
  justify-content: center;
  box-sizing: border-box;
  width: 650px;
  height: 800px;
  margin: 24px auto;
  background-color: var(--wpp-primary-color-100);
  border: 1px solid var(--wpp-grey-color-600);
  border-radius: 8px;
  opacity: 0.35;
}
</style>
