FROM node:20.14.0

WORKDIR /app

COPY . .

RUN npm ci --no-audit --progress=false

WORKDIR /app/packages/components-library-automation

RUN npm install

RUN npm install @playwright/test

RUN npx playwright install --with-deps

CMD ["npx","playwright", "test", "tests/functional-tests/"]
